### ISSUE TITLE
Conflict timezone with wordpress default timezone

### ISSUE THREAD

**Issue by KamranKhorsandi** [wordpress-parsi/wp-parsidate#1]
Should be remove :

```
$timezone = get_option( 'timezone_string' );
if ( $timezone != '' )
	date_default_timezone_set( $timezone );
else
	date_default_timezone_set( 'Asia/Tehran' );
```

**Comment by amiremami** [comment]
سلام. خسته نباشید
من ۲ باگ رو معرفی کرده بودم در پلاگین به مرتضی جان. یکی اینکه تاریخ پلاگین یوست نباید شمسی شه. یکی هم اینکه ربات گوگل قادر به خوندن تاریخ انتشار مطلب نیست، چون اونم شمسی می شه با پلاگین شما.
کد درستش هم فرستادم.
قرار بود قبل از عید هم این آپدیت منتشر شه

الان این آپدیت شامل رفع اینها هست؟ چون در چنج لاگ چیزی ندیدم
