### ISSUE TITLE
Uncaught SyntaxError: illegal character U+06F0 with gravity form

### ISSUE THREAD

**Issue by only-sadeghi** [wordpress-parsi/wp-parsidate#106]
Hi
when enable parsidate plugin, all the form created by GravityForms have error"Uncaught SyntaxError: illegal character U+06F0" in console. but when disable parsidate, issue fixed.
 
![image](https://user-images.githubusercontent.com/24185084/142718459-82f546f0-f790-4254-ac77-ff30b616e350.png)

thanks for new version :)

**Comment by mehrshaddarzi** [comment]
@only-sadeghi 

what is your Gravity-froms plugin version ?
have you installed `persian-gravity-forms` also ?

**Comment by only-sadeghi** [comment]
Gravity form version 2.5.15 and persian gravity form version 2.3.1.4

**Comment by hamidrezayazdani** [comment]
I tested with Gravity forms version 2.5.16 and Persian gravity forms version 2.5.15 and I could not reproduce this situation. There was no problem. So i close this issue.

**Comment by javad-rzvn** [comment]
The problem still exists!
Thanks to this issue, I could find out the problem was wp-parsidate plugin

**Comment by hamidrezayazdani** [comment]
The `U+06F0` is [**Extended Arabic-Indic Digit Zero**](https://charbase.com/06f0-unicode-extended-arabic-indic-digit-zero). What is the content of your page? Is converting numbers to Farsi active or not? Please provide more information so we can reproduce the situation.

**Comment by javad-rzvn** [comment]
It's in persian. Yes, it was active.
BTW, there is also a bug in sending scheduled post using wp-parsidate. The calendar disappears when I wanna set time!

**Comment by hamidrezayazdani** [comment]
The problem you have in Gravity Forms is a problem in the regex that converts the numbers inside the inline js tag, we will solve this problem soon.
Regarding the scheduling of posts, this problem has been solved and will not be present in the next release that will be released soon.

Thanks for your patience and support.
