### ISSUE TITLE
مشکل افزونه رنک مث

### ISSUE THREAD

**Issue by ghost** [wordpress-parsi/wp-parsidate#109]
@man4toman 

مرتضی جان مدتی هست افزونه rank math که فارسی سازی شده و در حال فروش هست یه سری تداخل با parsidate ایجاد میکنه و سایت رو با خطای 

```
$title variable required
```

دچار میکنه از اون طرف به هیچ وجه گردن گرفته نمیشه اگر میتونی اون پلاگین رو بررسی کن ببین داره چیکار میکنه که باعث تداخل شده مسئولیت پذیری اون طرف نزدیک به صفر هست

<br />

نویسنده لینک زیر رو نوشته:

https://virgool.io/rankmath/%D8%A8%D8%B1%D8%B1%D8%B3%DB%8C-%D8%AE%D8%B7%D8%A7%DB%8C-title-variable-required-%D8%AF%D8%B1-%D8%B1%D9%86%DA%A9-%D9%85%D8%AB-%D9%88-%DA%86%DA%AF%D9%88%D9%86%DA%AF%DB%8C-%D8%B1%D9%81%D8%B9-%D8%A2%D9%86-rtzq32ksxeup

در حالت کلی روش های فرساینده ای کار میکنه ولی بهتره این مشکل حل بشه

<br />

پاسخ فارسی ساز این افزونه در جواب تیکت من :

_این مشکل هیچ ارتباطی به رنک مث ندارد دوست خوبم. مشکل از فارسی سازهای صدسال بروز نشده و رایگان شماست که تداخل می اندازد_

لینک افزونه : 

https://www.zhaket.com/web/rank-math-pro

**Comment by Alireza-Naji** [comment]
درود بر شما امیر عزیز. این مشکل بر روی نسخه جدید رنک مث ژاکت بر طرف شده است. لطفا تیکت بزنید یا به شماره من در تلگرام پیام بدید تا بروزرسانی جدید را زودتر به شما بدم.  در نظر داشته باشید رنک مث ژاکت توسط بنده کاملا رصد می شود و با اینکه یک مقاله 5 دقیقه ای و یک راهکار 2 دقیقه ای برای آن وجود دارد باز هم پاسخ ها را آنطور که می خواهید برداشت می کنید. رنک مث با پارسی دیت بالاترین سازگاری را دارد و این موضوع را بارها در توییتر هم اعلام کرده ایم و در وب فارسی چندین فارسی ساز داریم. در مقاله صراحتا ذکر شده یکی از مواردی که می تواند به این خطا سو دهی کند فارسی سازها است که در کنار چندین موضوع دیگر عنوان شده. در هر صورت نسخه بروز شده را پیام بدهید تا ارسال کنم. 09155586990

**Comment by Alireza-Naji** [comment]
> درود بر شما امیر عزیز. این مشکل بر روی نسخه جدید رنک مث ژاکت بر طرف شده است. لطفا تیکت بزنید یا به شماره من در تلگرام پیام بدید تا بروزرسانی جدید را زودتر به شما بدم. در نظر داشته باشید رنک مث ژاکت توسط بنده کاملا رصد می شود و با اینکه یک مقاله 5 دقیقه ای و یک راهکار 2 دقیقه ای برای آن وجود دارد باز هم پاسخ ها را آنطور که می خواهید برداشت می کنید. رنک مث با پارسی دیت بالاترین سازگاری را دارد و این موضوع را بارها در توییتر هم اعلام کرده ایم و در وب فارسی چندین فارسی ساز داریم. در مقاله صراحتا ذکر شده یکی از مواردی که می تواند به این خطا سو دهی کند فارسی سازها است که در کنار چندین موضوع دیگر عنوان شده. در هر صورت نسخه بروز شده را پیام بدهید تا ارسال کنم. 09155586990

@amirshnll amirshnll

**Comment by ghost** [comment]
@Alireza-Naji 

<div dir="rtl">

علیرضا جان برادر ببین من که خدایی نکرده با شما یا کار شما مشکل ندارم اتفاقا تحسین میکنم و حدودا 10 نسخه از این افزونه لایسنس خریدم ولی شما احساس میکنی ما تازه یه سی پنل خریدیمو یه وردپرس نصب کردیم داریم صحبت می کنیم میگیم مشکل داره هیچی متوجه نیستیم.

من شخصا از ادبیات بالا به پایین در ادبیات نوشتاری شما در مورد مصرف کننده نهایی ناراحتم

سناریو خیلی پیچیده نیست وقتی یه چیزی داره عدم سازگاری میکنه رفعش میکنن صورت مسئله رو که پاک نمیکنن نمیشه که مثلا توی مورد a درست کار کنه توی مورد b خراب کار کنه باید تکلیفش روشن باشه یا کار میکنه یا نمیکن ؛ در حال حاضر برداشت من این هست که یک افزونه تداخل ایجاد میکنه و باید این مشکل اصولی حل بشه نه که من دوساعت یه بار بیام سایتو باز کنم ببینم مشکل داره یا نه اگر داره سریع نسخه شمارو بردارم اصلی رو نصب کنم درست بشه باز سوییچ کنم روی نسخه ی شما دقیقا کامپیوترها اومدن پیچیدگی کار مارو کم کنن نه که بار اضافی بزارن روی دوش ما

در مورد ارسال نسخه هم صبر میکنیم که از وندور اصلی شما نسخه منتشر کنی ما دانلود کنیم و نصب کنیم نیاز به تلگرام و دریافت زودتر از زمان انتشار نیست در هر حالت اگر کمکی از سمت من بر میومد من خوشحال میشم روی پروژه توی وقت آزادم کمک داشته باشم 🌹 

ولی مشکل اصلی که برای من ایجاد شده بود با پارسی دیت بود که منتظر میمونم یا این طرف حل بشه یا از طرف شما وقتی حل شد این issue رو میبندم مرسی از اینکه حداقل رصد میکنی که در مورد پروژه کجا نظر هست که بری پاسخ بدی این برای من ارزشمند بود

</div>

**Comment by Alireza-Naji** [comment]
درود جناب شکوری، نسخه جدید رنک مث ژاکت طی امروز فردا پس از تایید کیفی ادمین ژاکت منتشر می شود. مشکل فوق را با نسخه اصلی که خریده بودیم با پشتیبان رنک مث برطرف کردیم و در نسخه ژاکت تصحیح شد. حدود یک ماه است که تست گرفتیم روی چندین سایت که مشکل را داشتند و الان صد در صد با اطمینان نسخه بروزرسانی را منتشر می کنیم که با ارسال ایمیل از سمت ژاکت مطلع می شوید

در خصوص مواردی که فرمودید، صحبت کردن افراد با ادبیات مختلف تا جایی که توهین مستقیم شکل نگیرد، یک امر طبیعی است و هرگز بنا به سطح دانش افراد نیست.  هرچند تداخل و بحث اعداد فارسی در فروش ویژه یکی از مهم ترین سرنخ ها بود اما موضوع توسط توسعه دهنده و همکارمان در تیم کاملا رفع شده است. 

امیدوارم پاسخ ها حمل بر سو تفاهم نباشد. لطفا پس از نصب نسخه جدید مجدد بررسی بفرمایید. با درود
