### ISSUE TITLE
 مشکل آیکن‌های افزونه‌ها در پیشخوان با نسخه ۴ parsidate

### ISSUE THREAD

**Issue by mahdiar** [wordpress-parsi/wp-parsidate#113]
سلام
من به تازگی نسخه ۴ این افزونه را نصب کردم. خدا قوت به دوستان بابت توسعه این افزونه ;)

مشکلی که وجود دارد تکه کدی است که بابت فونت وزیر به افزونه اضافه شده که باعث می‌ؤود تا برخی افزونه‌ها و قالب‌ها که آیکنی به پیشخوان اضافه می‌کنند تصویرشان به درستی نشان داده نشود چون از آیکن خودشان استفاده می کنند. به عنوان مثال افزونه smart slider یا پوسته Divi . ممنون می‌شوم بررسی بفرمایید.

تکه کد مربوطه: 
`.dashicons,
.dashicons-before:before,
.wpseo-metabox-menu ul li span.dashicons:before {
 font-family:dashicons!important;
}`

**Comment by amirhp-com** [comment]
fixed in #112
