### ISSUE TITLE
چند باگ در افزوونه parsidate

### ISSUE THREAD

**Issue by 79ho3ein** [wordpress-parsi/wp-parsidate#115]
سلام @man4toman.

فرموده بودید که باگ هارو داخل گیتهاب گزارش بدم. لطفا این چند مورد رو برسی کنید.

1- وقتی وضعیت ووکامرس رو از در حال انجام به تکمیل شده تغییر میدم، تقویم پارسی دیت نمایش داده میشه که کلا ناقصه (مانع تغییر وضعیت میشه) https://prnt.sc/25mdlv4

2- .اگه فونت وزیر رو برای پیشخوان فعال کنیم، آیکون های المنتور در پیشخوان پنهان میشن https://prnt.sc/25lqgmb

3- اگه تاریخ ووکامرس رو شمسی کنیم، در بخش ایجاد کوپن (تاریخ انقضای کوپن) تاریخ به درستی نمایش داده نمیشه. مثلا تاریخ انقضا رو 17 دی 1400 تعیین کردم ، اما 1970/1/1 نمایش میده
.تاریخ انقضا رو تعیین کنید، ذخیره کنید، وقتی صفحه مجدد بارگزاری بشه تاریخ تغییر میکنه
در این قسمت درست نمایش داده میشه : https://prnt.sc/25koeyk
اما این قسمت خیر : https://prnt.sc/25kohq4

اما دو درخواست دیگه داشتم اگه در نظر بگیرید عالیه

1- سازگاری با المنتور : ویجت های فرم و شمارش معکوس المنتور نیاز به شمسی سازی تاریخ دارند.

2- تغییر فونت ویرایشگر المنتور : https://prnt.sc/26brd1l  در حال حاضر فقط افزونه المنتور فارسیه که فونت ویرایشگر المنتور رو تغییر میده. اگه این ویژگی رو به افزونه اضافه کنید عالیه.

خیلی ممنون

**Comment by amirhp-com** [comment]
سلام. 
1. شماره یک در #112 حل شد و منتظر مرج هستم.
2. شماره دو در #112 حل شد و منتظر مرج هستم.
3. شماره سه در #112 حل شده و منتظر مرج هستم
4. تغییر فونت المنتور به افزونه در #112 اضافه شده و منتظر مرج هستم : https://prnt.sc/KG4fWVBy01DU

**Comment by 79ho3ein** [comment]
ممنون از زحمات شما. مشخصه آپدیت چه زمانی منتشر میشه؟

**Comment by amirhp-com** [comment]
سلام ، متشکرم. 
بزودی به همراه ویرایشات دیگر

**Comment by 79ho3ein** [comment]
بازم ممنون، موفق باشید.
