### ISSUE TITLE
امکان فارسی سازی اعداد فیلد کد پستی ووکامرس

### ISSUE THREAD

**Issue by 79ho3ein** [wordpress-parsi/wp-parsidate#116]
سلام وقت شما بخیر

در حال حاضر اگه کاربران فیلد کد پستی رو با اعداد  فارسی پر کنن، زمان پرداخت خطا میده و حتما باید اعداد رو به لاتین وارد کرد تا بشه پرداخت رو انجام داد.
متاسفانه بدی این مشکل اینه که اگه کاربران کد پستی رو با اعداد فارسی پر کنن و خطا بده، نمیگه که حتما باید کد پستی رو با اعداد لاتین پر کنید. میگه خطایی وجود داره. بنابراین خیلی از کاربرا فکر میکنن که این باگه وب سایته و نمیتونن خرید رو انجام بدن.
در حال حاضر هم فقط افزونه ووکامرس فارسیه که فیلد کد پستی رو قابل فارسی تایپ کردن میکنه. اما افزونش مدام داخل پیشخوان وردپرس تبلیغ میزاره و  عذاب آوره افزونش.
اگه لطف کنید و امکان تایپ فارسی کد پستی ووکامرس رو به افزونه اضافه کنید واقعا عالی میشه.

لطفا در صورت امکان برسی کنید @man4toman 

خیلی ممنون.

**Comment by 79ho3ein** [comment]
با عرض سلام و خسته نباشید خدمت توسعه دهندگان عزیز.
خواستم بپرسم آیا این مورد در نسخه جدید اضافه خواهد شد؟ با تشکر

**Comment by man4toman** [comment]
سلام وقت بخیر
بله این امکان روی نسخه جدید وجود خواهد داشت.

**Comment by 79ho3ein** [comment]
ممنون از زحمات شما آقا مرتضی عزیز
