### ISSUE TITLE
تداخل پارسی دیت با افزونه المنتور

### ISSUE THREAD

**Issue by 79ho3ein** [wordpress-parsi/wp-parsidate#117]
سلام وق شما بخیر

وقتی افزونه پارسی دیت فعال باشه، نمایش **زمان نوشته** المنتور به مشکل میخوره. یعنی مثلا به جای اینکه 18:46رو نمایش بده ،  6 شهریور 1400 رو نمایش میده.
برای بازتولید این باگ، لطفا مراحل زیر را دنبال کنید.

1- داخل صفحه ای، ویجت عنوان المنتور رو اضافه کنید.
2- از داخل بخش تگ های داینامیک، **زمان نوشته** رو انتخاب کنید :  https://prnt.sc/ymXbJlw7DXY- قاعدتا فقط باید زمان رو نشون بده. مثلا 19:20 اما تاریخ رو نشون میده : مثلا  6 شهریور 1400

3- حالا افزونه پارسی دیت رو غیر فعال کنید، مجدد مراحل بالا رو انجام بدید. حالا بعد از انتخاب گزینه **زمان نوشته**، زمان رو نمایش میده. مثلا 18:46 ، که این درسته.

با تشکر

**Comment by amirhp-com** [comment]
سلام. مشکلی که گفتید در تست نسخه نهایی افزونه یافت نشد.

شات از پیج تست : https://prnt.sc/X8fc1F_qGGqL

شات از تنظیمات : https://prnt.sc/sxHTff4MlGp5

**Comment by 79ho3ein** [comment]
سلام مجدد

عجیبه، اما الانکه مجدد افزونه رو از مخزن دانلود کردم و نست کردم، مشکل حل شد!
ممنون از وقتی که گذاشتید.
