### ISSUE TITLE
Set Persian settings by default

### ISSUE THREAD

**Issue by hamidrezayazdani** [wordpress-parsi/wp-parsidate#124]
Based on the [WordPress philosophy](https://wordpress.org/about/philosophy/), it seems we should set the settings automatically as needed by default.

Also provide the necessary technical documentation to remove the "Hooks" option.

**Comment by man4toman** [comment]
Thank you @hamidrezayazdani 

As I remember, we had this type of auto-setup before, be we received a bunch of negative comments for that.
And after a while, we removed the settings.

If you think that it can be good to we add it again, we can create a poll for that to get users opinions.
