### ISSUE TITLE
درخواست 3 ویژگی مهم برای صفحه پرداخت ووکامرس

### ISSUE THREAD

**Issue by 79ho3ein** [wordpress-parsi/wp-parsidate#129]
سلام عرض میکنم خدمت تیم زحمت کش پارسی دیت

1- در افزونه ووکامرس فارسی ،امکان کنترل اعداد شماره تماس وجود دارد :  https://prnt.sc/mfHgX8y98cv9
به گونه ای که اگه کاربران تعداد ارقام شماره تماس غیر از 11 رقم وارد کنند ،  (مثلا 9 یا 12 رقم) ، نمیتونه سفارشش رو ثبت کنه و میگه شماره تماس صحیح نیست. **این ویژگی همچنین برای کنترل ارقام کد پستی که 10 رقمی هست هم در این افزونه وجود داره : https://prnt.sc/kO80ghmbbTCK**

2- مطابق [این](https://github.com/wordpress-parsi/wp-parsidate/issues/116) درخواست ، لطفا در صورت امکان ویژگی ارقام فارسی را به فیلد شماره تماس ووکامرس در صفحه پرداخت اضافه کنید. در حال حاضر  اگه کاربر اعداد رو به فارسی وارد کنه ، سفارش قابل ثبت نیست و کاربر یه جورایی فکر میکنه سایت مشکل داره. این ویژگی هم در افزونه ووکامرس فارسی وجود داره :  https://prnt.sc/6Bo-eTqnpZoj

نکته ای که باید بهش اشاره کنم ، اینه که افزونه ووکامرس فارسی به دلیل تبلیغات بسیار زیاد در پیشخوان وردپرس و همچنین باگ های جدی  (که توسعه دهندگان آن اهمیت نمیدن) بسیار آزار دهنده هستش و امید ما بر اینه که به جای ووکامرس فارسی ، از  پارسی دیت استفاده کنیم که بسیار بهتره.

ممنون از زحمات شما @man4toman  و سایر همکاران

**Comment by man4toman** [comment]
سلام وقت بخیر
ممنون از پیشنهاداتتون. برای نسخه جدید روی این موارد کار میشه.

**Comment by 79ho3ein** [comment]
ممنون از لطف شما. مشخصه نسخه جدید حدودا چه زمانی منتشر میشه؟

**Comment by man4toman** [comment]
نسخه جدیدی طی ۱۰ رو آینده منتشر میشه.
بعد این انتشار  روی مواردی که درخواست زدید کار میشه. احتمالا دو الی سه هفته‌ای نسخه جدید خواهیم داشت.

**Comment by 79ho3ein** [comment]
ممنون از شما. موفق باشید

**Comment by amirhp-com** [comment]
1. #134 
2. already integrated, [woocommerce.php#L458](https://github.com/wordpress-parsi/wp-parsidate/blob/master/includes/plugins/woocommerce.php#L458)
