### ISSUE TITLE
Interference with elementor plugin

### ISSUE THREAD

**Issue by 79ho3ein** [wordpress-parsi/wp-parsidate#136]
hi @man4toman 
If we activate the parsidate plugin, the [post time option](https://prnt.sc/9_0Q4jOjP_Mf) in elementor dynamic tags will have problems. Actually, instead of displaying the time, it displays the date.

**Bug production steps**
1- Install Persiandate and activate the [shamsi date option](https://prnt.sc/VWulA1tAnLoe).
2- Enter the elementor editor and add a title widget.
3- In the dynamic tags section, select [post time option](https://prnt.sc/9_0Q4jOjP_Mf).

After that, the date will be displayed instead of the time. Now disable the plugin or turn off the shamsi date option. The problem will be solved.

**If we set the WordPress language to English, this problem does not exist. But if we put it on Farsi, this problem will arise.**

Also, the time format must be on default for this bug to occur : https://prnt.sc/9wI1M0TXKbwo

Of course, this is not a very important bug. There is a solution for that. But it's a bug anyway.

thank you

**Comment by hamidrezayazdani** [comment]
Hi, thank you for your participation and patience. I tested this with different formats and unfortunately I couldn't reproduce this situation.

![issue-136](https://github.com/wordpress-parsi/wp-parsidate/assets/40775953/feeb973e-f2f9-4c87-b8f6-9b8ac58eb63c)

Please test with the latest version and let me know if you still experience this problem.
