### ISSUE TITLE
Iran Cities for WooCommerce

### ISSUE THREAD

**Issue by zarei-dev** [wordpress-parsi/wp-parsidate#138]
What's the best way for doing that?

I think we have 2 ways:

1. Register states and cities on plugin activation as Terms (Benefits: User can change/add/remove Cities)
2. Add states and cities by loading IR-state_cities.php every time (Benefits: No touch DB)

In way 2, I prefer to use something like this:
```php
	$cities['XX'] = array(
		'YYY' => array(
			'City ',
			'Another City'
		),
		'ZZZ' => array(
			'City 3',
			'City 4'
		)
	);
```
[Implementation example](https://github.com/8manos/wc-city-select)

**Comment by zarei-dev** [comment]
@man4toman 

In the second method, the user can change cities with a filter.

**Comment by man4toman** [comment]
Hi @zarei-dev 

Based on our experience, it is better to load this list from the code, it can be safe from users edit.

And please feel free to choose the best way :)

Thanks

**Comment by Michaelgimii** [comment]
This would be a super cool feature. Will the list of Iranian cities be added to parsidate plugin?

**Comment by zarei-dev** [comment]
@Michaelgimii 
Yes. I'm working on it.

**Comment by hamidrezayazdani** [comment]
Added in #152
