### ISSUE TITLE
اشتباه نوشتاری در توضیحات افزونه

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#147]
باسلام
 در قسمت نصب افزونه (در پیشخوان وردپرس) اون قسمتی که توضیحات افزونه و سایت افزونه درج شده اشتباه املایی وجود داره

متن:
بسته‌ی پارسی سازی وردپرس، اضافه‌کردن پشتیبانی کامل راست‌به‌چپ و تاریخ خورشیدی برای وردپرس. این افزونه از نوشته‌ها، دیدگاه‌ها، برگه‌ها، بایگانی‌ها، جستجو‌ها و دسته‌بندی‌ها و پیوندهای یکتا پشتیبانی می‌کند و تمام قسمت‌های مدیریت و ویرایشگر را پارسی می‌کند. این افزونه هم‌چنین یک بزارک بایگانی شمسی نیز دارد.

کلمه اشتباه: بزارک
کلمه اصلی: widget

متن اصلی:

Persian package for WordPress, Adds full RTL and Shamsi (Jalali) support for: posts, comments, pages, archives, search, categories, permalinks and all admin sections and TinyMce editor, lists, quick editor. This package has Jalali archive widget.

ابزارک رو به اشتباه نوشتید بزارک و خیلی وقته که اصلاح نشده.

**Comment by bihovi584om** [comment]
![Capture4443](https://user-images.githubusercontent.com/130480543/231778956-2597c50f-185d-4468-9aee-c179cd10eac6.PNG)

**Comment by hamidrezayazdani** [comment]
Solved in #150

**Comment by bihovi584om** [comment]
مرسی از شما اما در نسخه‌ای که در مخزن وردپرس هست این غلط املایی هنوز هست. (نسخه آخر 4.0.2 که در گیت هاب هست درسته)
آیا در آپدیت بعدی درست میشه؟
