### ISSUE TITLE
مشکل در شمسی شدن تاریخ بایگانی ها

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#148]
سلام

افزونه پارسی دیت رو در سایتی نصب کردم قسمت بایگانی های سایت رو به شمسی تبدیل میکنه اما متاسفانه تاریخ شمسی اشتباهه من فکر میکنم به اشتباه تاریخ اون صفحه رو به جای تاریخ پست ها نمایش میده

(منظورم صفحات بایگانی وردپرسه)

قالب انفولد نصب بود روی سایت و پارسی دیت 4.0.2 رو نصب کردم

لطفا بررسی کنید.

**Comment by bihovi584om** [comment]
مجدد بررسی کردم وقتی در یک صفحه لیست مقالات رو برای نمایش قرار میدی تاریخ انتشار اون صفحه رو به جای تاریخ پست ها نمایش میده.
دقیقا همینطور بود.

به طور مثال تاریخ انتشار صفحه ای که در اون مقالات رو برای نمایش قرار دادم تیر ۹, ۱۳۹۹ بود حالا در اون صفحه (که پست ها رو نمایش میداد) باز کردم دیدم تمام پست های سایتم رو تاریخ انتشارشون رو تیر ۹, ۱۳۹۹ نمایش میداد.

**Comment by bihovi584om** [comment]
این هم لینک برای اینکه این مشکل رو بهتر بررسی کنید:

https://themes.wpmonster.co/Enfold/new/medical/news/


مقالات صفحه بالا در تاریخ 25 تیر 1395 منتشر نشدن بلکه صفحه ای که اون مقالات در اونها نمایش داده میشن در اون تاریخ منتشر شده

مثلا داخل یک از اون مقاله ها بریم میبینیم که تاریخ انتشارش چیز دیگری هستش
مثلا این مقاله:
https://themes.wpmonster.co/Enfold/new/medical/a-small-gallery/

در 5 بهمن 1391 منتشر شده اما پارسی دیت در اون صفحه (بالا) که لیست مقالات رو نمایش میداد تاریخ رو میزنه 25 تیر 1395

لطفا مشکل افزونه رو اصلاح کنید.

**Comment by Amirali-Amirifar** [comment]
به نظر میرسه مشکل از شرت کد های صفحه ساز avia مخصوص انفولد هستش. مخصوصا وقتی که روی حالت مشبک انتخاب میشه.
کدی که فیلد تاریخ رو نشون میده به این صورت هست: 

`$meta_array['time'] = "<time class='slide-meta-time updated' {$markup_time}>" . get_the_time( get_option( 'date_format' ), $the_id ) . '</time>';`

که به خودی خود مشکلی نداره ولی وقتی پلاگین رو فعال میکنیم این مشکل به وجود میاد.

**Comment by bihovi584om** [comment]
سلام
این مشکل فقط در افزونه پارسی دیت دیده میشه من از افزونه های جلالی و wp-shamsi  استفاده کردم چنین مشکلی ندیدم حالا به همین خاطر نمیتونم از پارسی دیت استفاده کنم، ممنون میشم ببینید چرا جلالی و wp-shamsi چنین مشکلی ندارن از همون راهکار یا راهکار دیگه در اپدیت بعد پارسی دیت استفاده کنید تا این مشکل رفع بشه.

**Comment by bihovi584om** [comment]
این مشکل فقط در افزونه پارسی دیت دیده میشه من از افزونه های جلالی و wp-shamsi استفاده کردم چنین مشکلی ندیدم حالا به همین خاطر نمیتونم از پارسی دیت استفاده کنم، ممنون میشم ببینید چرا جلالی و wp-shamsi چنین مشکلی ندارن از همون راهکار یا راهکار دیگه در اپدیت بعد پارسی دیت استفاده کنید تا این مشکل رفع بشه.

**Comment by bihovi584om** [comment]
این مشکل فقط در افزونه پارسی دیت دیده میشه من از افزونه های جلالی و wp-shamsi استفاده کردم چنین مشکلی ندیدم حالا به همین خاطر نمیتونم از پارسی دیت استفاده کنم، ممنون میشم ببینید چرا جلالی و wp-shamsi چنین مشکلی ندارن از همون راهکار یا راهکار دیگه در اپدیت بعد پارسی دیت استفاده کنید تا این مشکل رفع بشه.

**Comment by Amirali-Amirifar** [comment]
درست میفرمایید. با بقیه پلاگین ها مانند Persian Date درست کار میکنه. باگ از خود پلاگین هست منتها اکتیو روش کار نمیکنن.

**Comment by hamidrezayazdani** [comment]
Fixed
#167 3cbd316
