### ISSUE TITLE
باگ در نمایش تاریخ در پنل وردپرس

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#149]
باسلام

در پیشخوان وردپرس تاریخ انتشار پست ها (و پست های زمانبندی شده) رو دوبار نمایش میده
مثال:

اگه فرمت نمایش تاریخ رو به این صورت تنظیم کرده باشیم (29, اردیبهشت, 1402)
به این صورت نمایش میده 29, اردیبهشت, 1402  29, اردیبهشت, 1402

یا هم اگه فرمت نمایش تاریخ رو به این صورت تنظیم کرده باشیم (29/02/1402)
به این صورت نمایش میده 29/02/1402  29/02/1402

تمام تاریخ ها رو دوبار دوبار نمایش میده؛
دقت کنید این باگ در پیشخوان وردپرس جایی که زمان و تاریخ انتشار پست ها نوشته شده وجود داره (و همچنین پست های برنامه ریزی شده در این قسمت)

**Comment by bihovi584om** [comment]
![Capture22](https://user-images.githubusercontent.com/130480543/231230542-7abde43b-938a-4dac-acaf-fd2cad4caee5.PNG)

**Comment by bihovi584om** [comment]
دوباره تست کردم با وردپرس خام و بدون هیچ افزونه ای و قالب پیش فرض 2023 وردپرس
دیدم مشکل داره

خود وردپرس بدون پارسی دیت تاریخ رو به این صورت درج میکنه

اگر امروز پستی رو منتشر کنید مینویسه امروز ساعت فلان مثلا: (امروز، 17:26)
اگر در ماه قبلی منتشر کرده باشد میتویسه (مارس 12th، 17:21)
اگر در سال قبل منتشر کرده باشی یا قبل اون به این شکل مینویسه (آوریل 10th 2019، 21:56)


اما در افزونه شما

اگر امروز منتشر کرده باشید مینویسه (امروز، 1402/01/24)
اگر در ماه قبلی منتشر کرده باشید مینویسه (اسفند 21ام، 1401/12/21)
اگر در سال قبل منتشر کرده باشی یا قبل اون به این شکل مینویسه (فروردین 21ام 1398، 1398/01/21)

میبینید؟ دوبار تاریخ رو درج کرده در ماه و سال های قبل رو که به احتمال زیاد باگی داشته باشه

عکس هم پایین تر در ج میکنم

هم از قسمتی فعالیت های وردپرس که این باگ رو دیدم و از قسمت ساختار تاریخ زمانم

**Comment by bihovi584om** [comment]
![Capture1111](https://user-images.githubusercontent.com/130480543/231786759-d7c7a197-ec88-4455-8ece-00e31112c1e1.PNG)

**Comment by bihovi584om** [comment]
![Capture111111122](https://user-images.githubusercontent.com/130480543/231788987-046e36f6-718d-498e-b36d-7db4268d8f7c.PNG)

**Comment by bihovi584om** [comment]
![Capture2222244](https://user-images.githubusercontent.com/130480543/231789224-0adad316-0371-4cc9-a853-b4dec9202860.PNG)

**Comment by bihovi584om** [comment]
![Capture33333](https://user-images.githubusercontent.com/130480543/231789396-317ed059-2c66-4408-a5ab-efaeff4cab70.PNG)

**Comment by bihovi584om** [comment]
باگ پارسی دیت در نمایش تاریخ دقیقا مربوط میشه به پست هایی که سال های قبل منتشر شدن و یا میخواییم پست جدید رو برای سال قبل منتشر کنیم

در بالا میبینید با توجه به اینکه من ساختا رو گزاشتم روی Y/M/D بازهم اینجوری نمایش میده پست سال های قبل رو

فروردین 21ام 1398، 1398/01/21

چرا باید دوبار تاریخ رو نمایش بده؟؟

**Comment by bihovi584om** [comment]
سلام
یعنی هیچ کس این گزارش باگ رو تا الان ندیده که پاسخی بده؟

باگ در نمایش تاریخ در پنل وردپرس

از تیم پارسی دیت خواهش میکنم اگه میشه این باگ رو هم در دست بررسی قرار بدید تا رفع بشه.
سپاس

**Comment by hamidrezayazdani** [comment]
Thank you for your participation and patience. I tested this with different date formats and unfortunately I couldn't reproduce this situation

![issue-149](https://github.com/wordpress-parsi/wp-parsidate/assets/40775953/52f922e1-6047-45fa-b52b-4b4d2ba23d6b)

**Comment by man4toman** [comment]
Fixed in [5.0.1 ](https://github.com/wordpress-parsi/wp-parsidate/releases/tag/5.0.1)
