### ISSUE TITLE
Shamsi Calendar

### ISSUE THREAD

**Issue by ElyDotDev** [wordpress-parsi/wp-parsidate#15]
Hi
I just saw the tweet about helping to add the editor's Shamsi/Jalali calendar. Just want to know more about it. Are you talking about the new Gutenberg editor? Is so, please explain more about the desired solution.

Also, you can assign the task to me. I will fix/enhance the parts that are needed to produce the feature.

**Comment by ElyDotDev** [comment]
Just checked the Gutenberg. Well, It's not an easy task. Gutenberg uses moment.js for date/time functionalities. But using the Jalali plugin of the moment, create an issue in this line [jalaali/moment-jalaali/blob/master/index.js#L446](https://github.com/jalaali/moment-jalaali/blob/master/index.js#L446). The issue needs to be checked further and currently I have no clue about the main cause of the issue. 

Second, the dateTimePicker of Gutenberg uses [react-dates](https://github.com/airbnb/react-dates). Based on [#975](https://github.com/airbnb/react-dates/issues/975), [#755](https://github.com/airbnb/react-dates/issues/755), [#578](https://github.com/airbnb/react-dates/issues/578) and [#488](https://github.com/airbnb/react-dates/issues/488) issues, which are open and not fixed, the date picker has an issue with Jalali date. The calendar will start from non-1 date.

To enable Jalali calendar in Gutenberg, At first the react-dates issue should be fixed and merged. Then some changes in Gutenberg should be done and that changes also should be accepted and merged. After all, we can add the functionality to parsidate.

**Comment by man4toman** [comment]
Thanks for your follow-up, please send me an email address and I will be in touch with you.

**Comment by ElyDotDev** [comment]
Just sent an email to ****[at]geransayeh.com
