### ISSUE TITLE
باگ در انتخابگر زمان پارسی دیت

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#150]
سلام
جایی که برای انتخاب زمان در پست ها قرار داره با فعالسازی و نصب پارسی دیت به به مشکل میخوره و نمیشه زمان رو انتخاب کرد
(توجه کنید: اول فکر کردم با قالب من مشکل داره پس رفتم روی یه سایت خام بدون هیچ پلاگینی و قالب 2023 خود وردپرس تست کردم دیدم بله مشکل داره بازهم)

**Comment by bihovi584om** [comment]
![Capture34](https://user-images.githubusercontent.com/130480543/231775345-9f9c0ad9-5170-42de-af7a-40c5b489da6d.PNG)

**Comment by bihovi584om** [comment]
عکس بالا انتخابگر زمان رو در پست وردپرس نشون میده که برای انتخاب زمان باید اون غربیلک کنار زمان رو تغییر جهت داد اما تا میام تغییر جهت بدم کل باکس بسته میشه (یعنی خصوصیت این باکس همینطوریه)

اما عکس زیر بدون نصب افزونه پارسی دیته که به راحتی بدون اون غربیلک میشه زمان رو دستی توی باکس نوشت اما زمانی که پارسی دیت نصب میشه دیگه نمیشه توی باکس زمان به صورت دستی زمان رو تغییر داد.

**Comment by bihovi584om** [comment]
![Capture456](https://user-images.githubusercontent.com/130480543/231778516-b6fec864-266e-49ad-b3af-3322dcf0da5d.PNG)

**Comment by hamidrezayazdani** [comment]
I wrote a new module for scheduling posts. In the next release, it will replace the current calendar and the problems will be solved.

https://github.com/hamidrezayazdani/wp-block-editor-post-scheduler

![Screenshot 2023-05-10 at 19-40-46 ویرایش برگه “نتایج قرعه کشی جوایز جشنواره عید تا عید” ‹ فروشگاه اینترنتی زز زاگرس — وردپرس](https://github.com/wordpress-parsi/wp-parsidate/assets/40775953/42cbd35a-edba-45b4-871f-532467ad10b1)

**Comment by man4toman** [comment]
Thanks @hamidrezayazdani
Please check the current github version for this request, as I know we fix it before.
Maybe at [here](https://github.com/wordpress-parsi/wp-parsidate/commit/2ee7d589f76bfcc261be443e7060feefa8d89da6).

**Comment by bihovi584om** [comment]
میشه از شما درخواست کنم رابط کاربری جدیدی برای این قسمت قرار ندید؟
رابط کاربری خود گوتنبرگ برای این قسمت عالیه و فقط شما به جای تاریخ میلادی، تاریخ شمسی قرار بدید (توی عکس بالا نسخه میلادی رو گذاشتم)

دوتا نکته:
اول) البته اگه نوشتن کد افزونه با من بود، زمان قسمت مدیریت وردپرس رو کلا روی میلادی میزاشتم و فقط تاریخ توی پست هاو بایگانی ها که به کاربر نمایش داده میشن رو شمسی سازی میکردم (چه اشکالی داره!)
دوم) حتی از نظرم اعداد هم در این بخش (مدیریت زمان انتشار پست ها) به صورت انگلیسی باشه مهم نیست چون فقط مدیر میبینه.
این دوتا نکته رو هم اگه گزینه ای براش در افزونه تون قرار بدید من استقبال میکنم

من فقط و فقط از یه تقویم وردپرس اینو میخوام؛ نمایش تاریخ داخل پست ها و بایگانی ها به شمسی (که البته پارسی دیت در بایگانی ها تاریخ اشتباه برمیگردونه)
