### ISSUE TITLE
پیشنهاد ادغام تقویم جلالی با پارسی دیت

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#151]
باسلام

لطفا با تیم افزونه وردپرس جلالی و وردپرس فارسی در ارتباط باشید تا تقویم جلالی رو با پارسی دیت جایگزین کنید هم در مخزن وردپرس و هم در گیت هاب و...

با توجه به اینکه دیگه قرار نیست افزونه وردپرس جلالی به روز بشه این اقدام شما میتونه جلوی مشکل امنیتی سایت های زیادی رو بگیره چون چیزی در حدود 40 هزار نصب فعال داره در حال حاضر و قرار نیست به روز بشه؛
برای خود بنده چون وردپرس رو به روز کردم و وردپرس جلالی از قبل نصب بود تاریخ پست ها خودکار به میلادی تبدیل شد و اول فکر کردم قالب یا افزونه ای تداخل داره یا مشکلی وجود داره اما بعد بررسی فهمیدم مشکل از به روز نشدن وردپرس جلالی هستش کاربرهای زیادی ممکنه مثل بنده دچار چنین مشکلی بشن
لطفا تقویم وردپرس جلالی رو با تقویم پارسی دیت ادغام کنید. با توجه به آمار نصب وردپرس جلالی (در صفحه خود افزونه) چیزی در حدود 40 هزار نصب فعال داره، این میتونه تعداد نصب فعال افزونه شما رو هم بالا ببره؛ کاربرها وقتی تو پنل وردپرسی شون اپدیت رو ببینند اقدام به اپدیت می کنن، (اقدام به اپدیت از جلالی به پارسی دیت)

به طورکلی منظورم اینه تقویم جلالی رو در مخزن وردپرس با پارسی دیت جایگزین کنید. و مدیریت اون هم مثل پارسی دیت توسط تیم شما انجام بشه.

قبلا یه پروژه دیگه تیم پارسی دیت برای وردپرس جلالی راه اندازی کرده بود که از پارسی دیت به عنوان هسته استفاده میکرد و در ظاهر از وردپرس جلالی استفاده میکرد* (Use Parsidate as core with main wp-jalali functions as mask)؛ از نظرم در این مورد نیاز نیست دوتا پروژه رو پیش ببرید کلا افزونه جلالی رو با پارسی دیت ادغام کنید.
لینک این پروژه:
https://github.com/wordpress-parsi/wp-jalali

**Comment by hamidrezayazdani** [comment]
@man4toman We talked about this before, is it possible? My suggestion is that a notice to Jalali users to switch to PersiDate will solve the problem

**Comment by man4toman** [comment]
Hi @hamidrezayazdani @bihovi584om 
Thanks for your suggestion.
We talked about this request with Jalali team about 2 years ago, as you can see, we create a official repo too, but there was some problems from Jalali owners.
Also, after this years, we figured out there is no benefit for us because all Jalali user still uses outdated WordPress that Parsidate can't work with them.
If we need a public announcement to all Persian WordPress users to notify about Parsidate, we can easily create a blog post in fa.w.org and put the Parsidate in official Persian WordPress package.

**Comment by bihovi584om** [comment]
سلام،

مرسی از شما و همکاری و مشارکتتون، بله با گفتن نکات دیدم کاملا حق با شماست؛
البته از طرفی افزونه پارسی دیت باگ های زیادی هنوز داره و اصلا برای قرار دادن داخل پکیج وردپرس فارسی اماده نیست!
مثلا گزارش های زیادی دیدم که با افزونه المتور سازگاری نداره و همچنین افزونه های پرطرفدار دیگه زیادی هستن که هنوز پارسی دیت باهاشون سازگار نیست.

وقتی داشتم تقویم های موجود وردپرس رو بررسی میکردم کاربری رو در تاپیک های وردپرس دیدم که درخواست اضافه شدن تاریخ شمسی در هسته وردپرس (به صورت بومی) رو داده بود از نظر شما چنین چیزی ایا ممکنه؟ شما نمیتونید چنین درخواستی رو به تیم وردپرس خارجی بدید یا در هسته وردپرس در این مورد همکاری کنید تا از تقویم شمسی پشتیبانی کنن؟ مثل ویندوز 10/11 که از تقویم شمسی پشتیبانی میکنن؟
اگه اشتباه نکنم اینه درخواست کاربری که در تاپیک ها دیدم:
https://wordpress.org/support/topic/add-solar-hijri-calendar-jalali-calendar-natively-in-wordpress/

مرسی.

**Comment by bihovi584om** [comment]
منم با گفته آقای حمیدرضا یزدانی موافقم، گفتم که برای خودم هم این موضوع کمی دردسر ایجاد کرد چون نمیدونستم توی بسته جدید وردپرس، جلالی دیگه نیست به پاس اینکه قبلا در بسته نصبی بوده و اطلاعیه ای هم از تیم وردپرس فارسی در این مورد ندیدم فکر کردم تداخل افزونه ها یا باگی چیزی باشه؛

اگه در جلالی یه اطلاعیه اضافه کنید که سپاس گزاریم از اینکه سایت تون رو به روز رسانی کردید؛ اقا /خانم محترم جلالی از وردپرس 6 به بالا پشتیبانی نمیکنه بنابراین تاریخ هیچ کدوم از پست ها و برگه های شما تبدیل به شمسی نمیشن لطفا برای عملکرد صحیح تقویم شمسی سایت تون، افزونه پارسی رو نصب کنید

اضافه کردن همین یه جمله کلی از مشکلات و سردرگمی کاربرانی که وردپرس رو اپدیت میکنن کم میکنه

مرسی از شما.

**Comment by man4toman** [comment]
متاسفانه ما دسترسی به افزونه جلالی نداریم. به همین دلیل امکان حرکت خاصی از سمت ما نیست.
فکر میکنم بحث خاصی در این زمینه باقی نمونده، من این ایشو رو میبیندم. :)
