### ISSUE TITLE
Suggestion to use Composer and PHPCS

### ISSUE THREAD

**Issue by zarei-dev** [wordpress-parsi/wp-parsidate#153]
Dear WordPress Parsi team,
I hope this message finds you well. I've been following your work on GitHub, and I think the project has a lot of potential. However, I noticed that there is no use of Autoload or Composer in the project, which can make it harder to maintain and update.

As you may know, Autoload and Composer are tools that can greatly simplify the codebase by automatically loading classes and managing dependencies. Additionally, using PHP Code Sniffer can help ensure that the code conforms to best practices and coding standards.

I would like to suggest that the WordPress Parsi team consider incorporating Autoload, Composer, and PHP Code Sniffer into the project. This could help make the project more efficient to maintain and easier to update, while also ensuring that the codebase follows best practices.

[WordPress coding standards](https://github.com/WordPress/WordPress-Coding-Standards) are a set of guidelines and best practices for writing code in WordPress projects. These standards cover everything from naming conventions and indentation to documentation and security practices.
Adhering to these standards can bring several benefits to a project, including:
- **Improved readability:** When everyone on a team follows the same coding standards, it makes the code easier to read and understand. This can help reduce errors and improve overall code quality.
- **Increased consistency:** Consistent code is easier to maintain and update over time. By following standardized practices, developers can ensure that their code is consistent with the rest of the project, making it easier for others to work with.
- **Better security:** Adhering to coding standards can also minimize potential security vulnerabilities in the code. For example, using proper sanitization and escaping techniques can help prevent SQL injections and cross-site scripting attacks.
- **Easier collaboration:** When working with large teams or across multiple projects, having common coding standards can make collaboration much easier. Developers can quickly understand each other's code, reducing the need for extensive communication and review.

I understand that implementing these tools may require some initial effort, but I believe that the benefits they provide will be well worth it in the long run. If needed, **I am happy to assist with the implementation process.**

Thank you for your time and attention to this suggestion. Please let me know if you have any questions or concerns.

Best regards,
Mohammad Zarei

**Comment by zarei-dev** [comment]
@man4toman @hamidrezayazdani 
Please check this issue.
thanks

**Comment by man4toman** [comment]
I'm going to close this issue due to inactivity, and we don't have any plan for use composer and phpcs for current roadmap.
@zarei-dev If you are interested to start it, feel free to create a new fork and after that let me know to create new branch for it,
Thanks
