### ISSUE TITLE
خالی بودن تاریخ و عدم امکان ویرایش و انتخاب تاریخ و برعکس بودن تاریخ

### ISSUE THREAD

**Issue by vekgithubb** [wordpress-parsi/wp-parsidate#154]
سلام و وقت بخیر و تشکر بابت پلاگینی که ایجاد کردید
میخوام 2 مشکل افزونه رو در بخش تاریخ گزارش کنم
1. هنگام ویرایش سفارش در قسمت انتخاب تاریخ، بعد از کلیک خالی نشون میده و بعد از عوض کردن ماه مثلا از مرداد به فروردین و دوباره انتخاب اون، تاریخ (روزهاش) به نمایش در میاد و میتونیم انتخاب کنیم البته بعد از انتخاب یا بعد از زدن دکمه ویرایش رو تست نکردم که ببینم درست عمل میکنه فعلا مشکل خالی نشان دادن رو خواستم گزارش بدم.
2. برعکس بودن تاریخ سفارشات در ووکامرس در هر افزونه فارسی سازی به همین صورته و در افزونه شما هم همینشکلیه تا حالا کسی کاری برای حل این مشکل انجام نداده. مثلا در ایمیل هایی که ارسال میشه تاریخ برعکس هست، یا در بخش نظرات محصولات تاریخ برعکس به نمایش در میاد. اگاه بتونید این مشکل رو هم حل بکنید ممنون میشم و مورد نیاز خیلی هاست. البته این مشکل برعکس بودن تاریخ بعضا در بخش نظرات مطالبم دیده میشه.
![2023-08-28_094356](https://github.com/wordpress-parsi/wp-parsidate/assets/101319125/d07f61f7-7876-4421-9df0-d8d6a7e44b20)
![263610647-67502429-8413-475b-b1ad-e2e8e1fb8a9e](https://github.com/wordpress-parsi/wp-parsidate/assets/101319125/a96a9d65-2850-44d8-b61a-51e64e3f10d7)

**Comment by hamidrezayazdani** [comment]
#167 a266e05

**Comment by paulvek** [comment]
در نسخه ی اخیر 5.0.1 مشکل تاریخ در بخش ویرایش سفارش حل شده، اما هنوز مشکل برعکس بودن تاریخ در ایمیل های ارسالی و... وجود داره.
