### ISSUE TITLE
مشکل تاریخ در بخش گزارشات و تجزیه و تحلیل

### ISSUE THREAD

**Issue by vekgithubb** [wordpress-parsi/wp-parsidate#155]
ابتدا تشکر میکنیم از بابت زحماتی که میکشید و پلاگین خوبی که ایجاد کردید

مدتهاست پلاگین آپدیت نشده، آیا آپدیت های جدیدی برای افزونه ارائه میکنید؟ از آخرین باری که آپدیت کردید نسخه های زیادی از ووکامرس و ووکامرس فارسی اومده

و اما مشکلی که داریم این هست که در بخش گزارشات (قدیمی) و تجزیه و تحلیل (جدید) امکان تنظیم نمایش با تاریخ شمسی و انتخاب تاریخ شمسی وجود نداره، و گزارشات و تجزیه و تحلیل ها به میلادی و باتوجه به تاریخ و سال میلادی هست. البته این مشکل از اولین روزی که این بخش جدید به ووکامرس اضافه شد برای کاربران فارسی زبان وجود داشت چون احتمالا هیچ کاری براش انجام نشده تا حالا و ممنون میشیم که شما برای فارسی و شمسی و بومی سازی این بخش در پلاگین خوبتون کاری انجام بدید

لطفا به تصایری که در زیر برای شما آپلود کردیم نگاه کنید. باتشکر

https://s8.uupload.ir/files/img1_y9wb.png
https://s8.uupload.ir/files/img2_2kum.png
https://s8.uupload.ir/files/img3_cwgz.png
https://s8.uupload.ir/files/img4_ltes.png
https://s8.uupload.ir/files/img5_1zln.png

هر سه تنظیمگر تاریخ و انتخابگر شمسی فعال هست

**Comment by hamidrezayazdani** [comment]
با سلام. ممنون از مشارکت شما.
در خصوص بخش «تجزیه و تحلیل» در ووکامرس، این بخش react-based هست و امکان اینکهه بتونیم با هوکها به سادگی کار کنیم وجود نداره. در واقع باید بر اساس پکیج WooCommerce Admin نوشته و بیلد بشه تا بشه ازش استفاده کرد.

در صدد هستیم که یک افزونه مجزا در نقشه راه پارسی‌دیت تعریف کنیم و پس از اینکه بازخورد کاربران رو دریافت کردیم و مشکل حادی نداشت با پارسی‌دیت ادغامش کنیم.

در خصوص گزارشات کلاسیک ووکامرس هم باید عرض کنم که حجم کدنویسی این بخش به دلیل نیاز به بازنویسی کوئری‌های دیتابیس برای دریافت گزارشات خیلی زیاده و از طرفی این بخش منسوخ شده پس ما تمرکزمون بر روی همون بخش «تجزیه و تحلیل» خواهد بود.
