### ISSUE TITLE
گزارش تداخل با Easy Watermark

### ISSUE THREAD

**Issue by ghost** [wordpress-parsi/wp-parsidate#157]
سلام و عرض ادب، افزونه با پلاگین [Easy Watermark](https://wordpress.org/plugins/easy-watermark/) تداخل داره
![132456](https://github.com/wordpress-parsi/wp-parsidate/assets/150959780/db55185d-85b1-4262-a17a-23010cf42f5b)
![237867](https://github.com/wordpress-parsi/wp-parsidate/assets/150959780/bd801b28-3d5e-4619-a4b3-77607593a0a9)

### Message

Function is_feed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. (This message was added in version 3.1.0.)

### Caller

is_feed()
wp-includes/query.php:417

wpp_is_feed()
wp-content/plugins/wp-parsidate/includes/general.php:119

disable_wpp()
wp-content/plugins/wp-parsidate/includes/plugins/disable.php:28

wpp_fix_i18n()
wp-content/plugins/wp-parsidate/includes/fixes-dates.php:164

apply_filters('wp_date')
wp-includes/plugin.php:205

wp_date()
wp-includes/functions.php:314

date_i18n()
wp-includes/functions.php:192

EasyWatermark\P\A\AttachmentUploadDate->__construct()
wp-content/plugins/easy-watermark/src/classes/Placeholders/Attachment/AttachmentUploadDate.php:26

EasyWatermark\Placeholders\Defaults->load_default_placeholders()
wp-content/plugins/easy-watermark/src/classes/Placeholders/Defaults.php:75

do_action('easy-watermark/placeholders/load')
wp-includes/plugin.php:517

EasyWatermark\Placeholders\Resolver->load_placeholders()
wp-content/plugins/easy-watermark/src/classes/Placeholders/Resolver.php:57

EasyWatermark\Placeholders\Resolver->__construct()
wp-content/plugins/easy-watermark/src/classes/Placeholders/Resolver.php:47

Micropackage\Singleton\Singleton::get()
wp-content/plugins/easy-watermark/vendor/micropackage/singleton/src/Singleton.php:58

EasyWatermark\Watermark\Handler->__construct()
wp-content/plugins/easy-watermark/src/classes/Watermark/Handler.php:87

EasyWatermark\Core\Plugin->get_watermark_handler()
wp-content/plugins/easy-watermark/src/classes/Core/Plugin.php:217

EasyWatermark\Features\WatermarkPreview->__construct()
wp-content/plugins/easy-watermark/src/classes/Features/WatermarkPreview.php:67

EasyWatermark\Core\Plugin->setup()
wp-content/plugins/easy-watermark/src/classes/Core/Plugin.php:102

do_action('plugins_loaded')
wp-includes/plugin.php:517

**Comment by hamidrezayazdani** [comment]
Fixed #167 3150f05
