### ISSUE TITLE
تداخل با انتخاب تاریخ acf

### ISSUE THREAD

**Issue by ghost** [wordpress-parsi/wp-parsidate#160]
سلام و عرض ادب، انتخابگر تاریخ افزونه با فیلد تاریخ acf تداخل داره، وقتی افزونه فعاله فیلد تاریخ ذخیره نمیشه
چطور باید انتخابگر تاریخ افزونه رو غیرفعال کرد کلا؟

**Comment by man4toman** [comment]
Hi @oldVtrN 
We are working on this bug in #164, thanks.
