### ISSUE TITLE
ناسازگاری با نسخه جدید وردپرس 6.4.2

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#161]
سلام و تشکر بابت افزونه خوبتون. مدت هاست هیچ بروزرسانی ای ارائه نشده. در مخزن نزدیک به 12 ماه از آخرین آپدیت میگذره. واقعا این پلاگین حیفه.
یک مشکل جدیدی که بهش برخوردیم اینه که در نسخه جدید از نظر ظاهری هم بهم ریختگی داره و در تصویر پیوست شده مشخص و قابل مشاهدست.
![parsi](https://github.com/wordpress-parsi/wp-parsidate/assets/153482922/4614762c-ed2f-412f-a501-2c53bdf64b44)

**Comment by man4toman** [comment]
Hi @paulvek 
The development is in progress, and about the UI issue, we are working on it in #164.

**Comment by paulvek** [comment]
Thank you Mr. Geransayeh @man4toman. It is a very good time for a change. Because there have been many fundamental changes in WordPress and especially in WooCommerce 8.5.1 We are waiting impatiently.
