### ISSUE TITLE
Minor Issues in beta version

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#164]
- [x]  Date picker corrupted in post screen
- [x] Incorrect order **date** after order **update/edit** (Woocommerce) (1,2)
- [x] Incorrect sale price date after product **update/edit** (Woocommerce)
- [x] ACF date field shows wrong date, also it seems can't be save!
- [x] Port current settings to default WordPress settings page (users requests)
- [x] When Woo Persian date is not active, the date picker shows incorrect date (3).

![image](https://github.com/wordpress-parsi/wp-parsidate/assets/935397/07beae3b-b2a5-4902-9976-ab027d54ad07)
![image](https://github.com/wordpress-parsi/wp-parsidate/assets/935397/88f0f385-1c35-42a9-aede-8145f62bc545)
![image](https://github.com/wordpress-parsi/wp-parsidate/assets/935397/9b8b1600-734c-418b-8f7c-193d9d92b355)

**Comment by paulvek** [comment]
Also add that when the plugin is active and images with long Farsi names are uploaded, as soon as you disable your plugin, the images in Elementor's display blocks and similar things get errors and are not loaded correctly, then again by activating your plugin. The pictures are shown correctly!
This is not for the beta version, I say about the 4.0.2 version. last original release in wordpress.org I did not test the beta version.
It is possible that when your plugin is active, the names of the images are stored incorrectly in the database. After deactivating, some images are not available in Elementor blocks. It is possible that your plugin has a bug and makes changes and hard queries in the database.

**Comment by man4toman** [comment]
Hi @paulvek 
I'll check the issues that you have with Elementor asap.

**Comment by hamidrezayazdani** [comment]
#167
