### ISSUE TITLE
مشکل فونت بخش ادمین در افزونه پارسی دیت

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#166]
در ویرایشگر وردپرس بعد از فعالسازی افزونه پارسی دیت مشکلی پیش میاد. مثلا در حالت ویرایشگر کلاسیک (در گوتنبرگ تست نکردم) متنی که داخل بخش اصلی مینویسیم کاملا بولد هست. احتمالا این به خاطر اینه که شما از وزن های مختلف فونت وزیر استفاده نکردید (تعریف نکردید) یا اینکه برای این بخش از آدرس یک فونت بولد یا مدیوم استفاده کردید این باعث میشه که کل متن به صورت بولد نشان داده بشه که در ویدیوی این تاپیک مشخصه.
حتی تفکیک فونت غیربولد و بولد از هم ممکن نیست چون همه به صورت بولد نشان داده میشه که تجربه کاربری رو خراب میکنه و کار سخت میشه.

همانطور که در ویدیو میتونید ببینید من vazir رو به vazirmatn تغییر دادم و مشکل حل شد همچنین فونت رو از 13 به 15 تغییر دادم که دید بصری بهتری داره 13 با توجه به رزولوشن مانیتور و حتی موبایل های امروزی دیگه مورد استفاده قرار نمیگره و برای این بخش مناسب نیست حداقل 14 تا 15 بهتره.

البته در این صورت درست شد که من فونتی با نام vazirmatn با وزن های مختلف تعریف کردم، بنابراین شما هم میتونید از این نسخه از فونت مرحوم راستی کردار استفاده کنید که هم کاملتره و هم وزن های مختلف داره و بسیاری از مشکلات وزیر سنتی در اون حل شده بوده.

میشد این رو از طریق کاستوم سی اس اس در وردپرس همچنین در کاستوم سی اس اس مرورگر حل کرد اما به صورت ریشته ای هنوز در پلاگین مشکل وجود داره و بهتره در خود پلاگین درست بشه تا هیچ کاربری مشکلی با اون نداشته باشه و بتونه بدون کار اضافه و هیچ تغییری از پلاگین شما استفاده کنه.

در مسیر زیر در پوشه افزونه
`https://example.com/wp-content/plugins/wp-parsidate/assets/css/editor.min-rtl.css`

در صورتی که کدهای زیر (پیشفرض)
`body,#tinymce{font-family:Vazir,tahoma,arial;font-size:13px;direction:rtl}p{margin-top:13px;margin-bottom:13px}h1,h2,h3,h4,h5,h6{margin-top:15px;margin-bottom:15px}`

را به کد زیر
`body,#tinymce{font-family:vazirmatn,tahoma,arial;font-size:15px;direction:rtl}p{margin-top:13px;margin-bottom:13px}h1,h2,h3,h4,h5,h6{margin-top:15px;margin-bottom:15px}`

تغییر بدید مشکل فونت حل میشه

https://github.com/wordpress-parsi/wp-parsidate/assets/153482922/af463e95-f9cc-402d-9b96-f073e6006358

به صورت GIF

![Video_2024-03-06_113737](https://github.com/wordpress-parsi/wp-parsidate/assets/153482922/c8c87f40-66e2-4501-b535-9b45586a8e83)

**Comment by paulvek** [comment]
بررسی بیشتری انجام دادم در نتیجه شرح بیشتری میدم برای اینکه بهتر متوجه مشکل بشید و بتونید راحت تر مشکل رو حل کنید.
مشکل یاد شده در آخرین نسخه پایدار مخزن 4.0.2 وجود داره. پوشه fonts در این نسخه کاملا خالی هست اما شما در فایل های سی اس اس مسیر فونت رو از داخل همین پوشه ای که خالی از هرنوع فونتی هست با فرموت woff2 تعریف کردید از اونجایی که درون این پوشه به اشتباه خالی از فونت گذاشته شده در نتیجه فونت نمیتونه لود بشه و فونت بعدی لود میشه یعنی tahoma در مورد بولد نمیدونم این از کجا داره فراخوانی میشه
نکته ی جالبی که وجود داره اینه که اگه فونت ها رو خودمون درون پوشه فونتس قرار بدهیم و تمام کدهای سی اس اس رو اصلاح کنیم (برخلاف چیزی که در بالا گفته بودم و فقط در inspect قابل تغییره! و با تغییر فایل ها) با تغییر فایل ها و تعریف وزن صحیح و ... هیچ تغییری نمیکنه! انگار مشکلی وجود داره یا وردپرس خودش به صورت خودکار از درون مخزن فایل ها رو بروز میکنه یا از جای دیگری فراخوانی میشه. چون با هر تغییر و خالی کردن کش هم مشکل برطرف نمیشه.
در نسخه 5.0.0 RC1 این مشکل برطرف شده (باقی موارد رو بررسی نکردم ببینم آیا مشکلات دیگری داره یا نه) ولی فقط از نظر اندازه! در این نسخه فونت ها رگولار و بولد در پوشه قرار داده شده، آدرس دهی ها انجام شده ولی به جای فونت vazir فونت tahoma نشان داده میشه و باز هم در لود فونت مشکلی وجود داره. تمام تست ها با ویرایشگر کلاسیک گرفته شده و با گوتنبرگ تست نگرفتیم.
با تمام اینها مدت هاست مشکلات زیادی توسط کاربران داره گزارش میشه که این فقط یکی از اونهاست. توسط خودم مشکلات دیگری گزارش شده و توسط کاربران دیگر مشکلاتی در گیتهاب و انجمن (مخزن) وردپرس، خیلی از مشکلات هم هست که کاربران یا گزارش نکردن یا نمیدونن چطور گزارش کنن یا این وقت رو ندارد/ یا نمیذارن که انجام بدن.
به هر حال امیدواریم که زودتر یک نسخه پایدار و جدید مطابق با آخرین تغییرات وردپرس و ووکامرس ارائه بشه.
در مخزن خطای زیر وجود داره. همچنین Last updated:1 year ago هست. بی شک شما زحمات زیادی میکشید و لطف میکنید و ما کماکان منتظریم.
`This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.`

**Comment by hamidrezayazdani** [comment]
#167 Fixed
![Screenshot 2024-03-07 at 12-00-09](https://github.com/wordpress-parsi/wp-parsidate/assets/40775953/fafbbcf8-64d3-465a-9ae0-3bd4d895c6ea)

**Comment by paulvek** [comment]
@hamidrezayazdani
ممنون بابت پیگیری.
اما احتمالا تغییرات رو در فایل های (مینیمایز) ایجاد نکردید و در فایل های اصلی ایجاد شده
چون وقتی حالت اشکال زدایی (گزینه ای در تنظیمات افزونه) فعال هست تا فایل های غیرفشرده شده اجرا بشه فونت درست نشون داده میشه به همین صورتی که در تصویر ارسالی شما نشان داده میشه. یعنی فونت های بولد و نرمال و کلا به طور صحیح نشان داده میشه.
اما وقتی این حالت غیرفعال باشه و فایل های (مین) لود میشن، تمامی فونت ها بولد هستند یعنی کل متنی که نشان داده میشه با فونت ضخیم دیده میشه چه در واقع بولد باشن یا بولد نباشن.
برای نمونه مقایسه این دو فایل رو مشاهده بفرمایید

**editor-rtl.css**

`

@font-face {
  font-family: Vazir;
  src: url("../fonts/Vazirmatn-Regular.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: swap
}

@font-face {
  font-family: Vazir;
  src: url('../fonts/Vazirmatn-Bold.woff2') format("woff2");
  font-weight: bold;
  font-style: normal;
  font-display: swap
}

body,
#tinymce {
  font-family: Vazir, tahoma, arial, serif;
  font-size: 13px;
  direction: rtl
}

p {
  margin-top: 13px;
  margin-bottom: 13px
}

h1,
h2,
h3,
h4,
h5,
h6 {
  margin-top: 15px;
  margin-bottom: 15px
}

`

و

**editor-rtl.min.css**

`

@font-face {
    font-family: Vazir;
    src: url(../fonts/Vazirmatn-Regular.woff2) format("woff2");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}
@font-face {
    font-family: Vazir;
    src: url(../fonts/Vazirmatn-Bold.woff2) format("woff2");
    font-weight: 700;
    font-style: normal;
    font-display: swap;
}
#tinymce,
body {
    font-family: Vazir, tahoma, arial, serif;
    font-size: 13px;
    direction: rtl;
}
p {
    margin-top: 13px;
    margin-bottom: 13px;
}
h1,
h2,
h3,
h4,
h5,
h6 {
    margin-top: 15px;
    margin-bottom: 15px;
}


`

![compare](https://github.com/wordpress-parsi/wp-parsidate/assets/153482922/1541b7a5-9bcc-4015-b8df-f3528d8fbf26)

این رو به عنوان نمونه فرستادم تا ببینید احتمالا برای باقی فایل ها هم همینطوره.
