### ISSUE TITLE
مشکل فونت افزونه و یکسان نبودن کدهای فایل های min و نرمال

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#168]
احتمالا تغییرات رو در فایل های (مینیمایز) ایجاد نکردید و در فایل های اصلی ایجاد شده
چون وقتی حالت اشکال زدایی (گزینه ای در تنظیمات افزونه) فعال هست تا فایل های غیرفشرده شده اجرا بشه فونت درست نشون داده میشه به همین صورتی که در تصویر ارسالی شما نشان داده میشه. یعنی فونت های بولد و نرمال و کلا به طور صحیح نشان داده میشه.
اما وقتی این حالت غیرفعال باشه و فایل های (مین) لود میشن، تمامی فونت ها بولد هستند یعنی کل متنی که نشان داده میشه با فونت ضخیم دیده میشه چه در واقع بولد باشن یا بولد نباشن.
برای نمونه مقایسه این دو فایل رو مشاهده بفرمایید

**editor-rtl.css**

`

@font-face {
  font-family: Vazir;
  src: url("../fonts/Vazirmatn-Regular.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: swap
}

@font-face {
  font-family: Vazir;
  src: url('../fonts/Vazirmatn-Bold.woff2') format("woff2");
  font-weight: bold;
  font-style: normal;
  font-display: swap
}

body,
#tinymce {
  font-family: Vazir, tahoma, arial, serif;
  font-size: 13px;
  direction: rtl
}

p {
  margin-top: 13px;
  margin-bottom: 13px
}

h1,
h2,
h3,
h4,
h5,
h6 {
  margin-top: 15px;
  margin-bottom: 15px
}

`

و

**editor-rtl.min.css**

`

@font-face {
    font-family: Vazir;
    src: url(../fonts/Vazirmatn-Regular.woff2) format("woff2");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}
@font-face {
    font-family: Vazir;
    src: url(../fonts/Vazirmatn-Bold.woff2) format("woff2");
    font-weight: 700;
    font-style: normal;
    font-display: swap;
}
#tinymce,
body {
    font-family: Vazir, tahoma, arial, serif;
    font-size: 13px;
    direction: rtl;
}
p {
    margin-top: 13px;
    margin-bottom: 13px;
}
h1,
h2,
h3,
h4,
h5,
h6 {
    margin-top: 15px;
    margin-bottom: 15px;
}

`

![compare](https://github.com/wordpress-parsi/wp-parsidate/assets/153482922/1541b7a5-9bcc-4015-b8df-f3528d8fbf26)

این رو به عنوان نمونه فرستادم تا ببینید احتمالا برای باقی فایل ها هم همینطوره.

@hamidrezayazdani
_Originally posted by @paulvek in https://github.com/wordpress-parsi/wp-parsidate/issues/166#issuecomment-1987111491_

**Comment by hamidrezayazdani** [comment]
Fixed #174

**Comment by paulvek** [comment]
تشکر. در نسخه master که چند ساعت پیش منتشر کردید این مشکل حل شد فقط احساس میکنم 2 تغییر دیگر نیازه
```
    font-size: 14px;
    line-height: normal;
```
یعنی تغییر اندازه فونت p درون ویرایشگر از 13 به حداقل 14px و یکی هم تعریف line-height نرمال هست چون الان خطوط خیلی به هم چسبیده هستن (در ویرایشگر کلاسیک)
