### ISSUE TITLE
برعکس بودن تاریخ در ایمیل های سفارش و بخش کامنت محصولات

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#169]
در نسخه ی اخیر 5.0.1 مشکل تاریخ در بخش ویرایش سفارش حل شده، اما هنوز مشکل برعکس بودن تاریخ در ایمیل های ارسالی و... وجود داره.

_Originally posted by @paulvek in https://github.com/wordpress-parsi/wp-parsidate/issues/154#issuecomment-1987116395_

**Comment by hamidrezayazdani** [comment]
Fixed #174

**Comment by paulvek** [comment]
سلام و تشکر بابت پیگیری ها و رفع مشکلات. متاسفانه مشکل برعکس بودن تاریخ در ایمیل ها و همچنین در بخش کامنت محصولات حل نشده.
