### ISSUE TITLE
Dashboard page warrning

### ISSUE THREAD

**Issue by ElyDotDev** [wordpress-parsi/wp-parsidate#17]
When the plugin is active, at the dashboard page a warning will be shown.

```PHP
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wpp_add_dashboard_widgets' not found or invalid function name in E:\wp-parsidate\wp-includes\class-wp-hook.php on line 286
```

The issue is at here: [wp-parsidate.php#L65](https://github.com/wordpress-parsi/wp-parsidate/blob/master/wp-parsidate.php#L65). The cause of the issue is that ```wpp_add_dashboard_widgets``` function is not defined. I search the plugin code and couldn't find the function. It seems that the function is removed in previous versions but register action was not deleted.

It can be fixed just by removing 65 line.

**Comment by man4toman** [comment]
Nice catch, thanks @alirdn .
