### ISSUE TITLE
بروز نبودن دیتای مشخصات افزونه

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#170]
از نسخه 5.0.1 استفاده میکنم اما در بخش افزونه های نصب شده نگارش 5.0.0 RC1 نشان داده میشه

**Comment by man4toman** [comment]
سلام نسخه بتا هست و جهت تست ریلیز شده.
بعد از تکمیل نهایی مشخصات افزونه در همه بخشها به روز میشه.
