### ISSUE TITLE
مشکل آیکون تاریخ

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#171]
سلام
گویا چند وقتیه برای توسعه این افزونه نسبت به قبل خیلی فعال شدید سپاس از تلاش شما برای توسعه این افزونه، سپاس از همگی؛

نسخه اخر یعنی 5.0.1 در قسمت انتخابگر تاریخ آیکونش به درستی نمایش داده نمیشه اولش که من فکر کردم کلا نمیشه تاریخ رو غیر از اون لیست چیز دیگه داد :)

![Screenshot 2024-03-10 161643](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/819a1f53-fab0-45db-aa01-2fef85e976ba)

در عکس بالا مشخصه
 در ضمن اگر از ظاهر خود گوتنبرگ استفاده میکردیدو در همون تاریخ های ایران رو جایگزین میکردید بسیار ریباتر و همچنین کاربردی تر میشد (چون میشه تاریخ رو دستی واردش کرد نیاز نیست از اون دراپ داون تاریخ درخواستی مون رو انتخابش کنیم)

![Screenshot 2024-03-10 162516](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/10fe0fa6-af81-4663-bc95-21e840e0c8ca)

در همین مورد باید بگم در خود گوتنبرگ زمان انتشار (ساعت انتشار) رو کلا باید دستی نوشت و تاریخ رو از دو طریق میشه انتخاب کرد یکی دستی بنویسی و دیگری از دراپ داون و اسکرول اون تاریخ مدنظر رو پیدا کنی و انتخاب کنی که راحتی بیشتری در انتخاب تاریخ نسبت به پارسی دیت به کاربر میده اما ساعت انتشار رو باید حتما دستی نوشت
از نظرم گوتنبرگ خیلی بهتر طراحی کرده این قسمت رو اگه میشه این قسمت رو بازنگری کنید و مثل گوتنبرگ طراحیش کنید

همچنین مورد دیگه اینکه در قسمت انتخاب تاریخ انتشار پارسی دیت وقتی با ماوس کلیلک میکنیم مربعی دور انتخاب زمان میاد که وقتی کلیک نکردی کادری دورش نیست این احتمال داره که کاربر احساس کنه که حتما باید با اون گزینه بالا و پایین انتخاب زمان و کلیک روی اونها زمان رو تنظیم کنه از نظرم اگه اون کادر مربع همیشه دور زمان (ساعت انتشار) باشه بهتره
![Screenshot 2024-03-10 163401](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/1a0f9de8-42e9-4090-924a-b2be6dbc31b1)

مرسی.

**Comment by hamidrezayazdani** [comment]
Hello. Thank you for your participation.

We are currently using the following package for post scheduling:

[wp-block-editor-post-scheduler](https://github.com/hamidrezayazdani/wp-block-editor-post-scheduler)

Currently, the initial version of this package has been developed. We tried to have the closest design to WordPress, considering the limitations that block editor development creates for us. Definitely, this design will be improved in the future, but note that this package is a free project and only one developer is currently developing it.

The icon problem was also fixed ;)

**Comment by hamidrezayazdani** [comment]
#174
