### ISSUE TITLE
پیشنهاد برای ویجت تاریخ

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#172]
سلام

ویجت تاریخ پارسی دیت (قسمت فعالیت داخل داشبورد وردپرس) تاریخ انتشار و زمان بندی پست هارو به شکل زیر نمایش میده

![Screenshot 2024-03-10 164717](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/8fff6644-be5f-44c7-ad59-703664451a4a)

بهتره که این شکلی نمایش داده بشه چون تاریخ ها در فارسی معمولا به این شکل خونده میشن(معمولا نمیگن اسفند 28 1402 میگن 28 اسفند 1402):

![Screenshot 2024-03-10 164717](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/b7c063a9-1619-4b55-a279-9d7cc17dce1b)

مرسی از شما مشارکت کننده ها.

**Comment by hamidrezayazdani** [comment]
Hi, I think this is related to the date display format that you specified in the WordPress settings. Have you tried another format?

**Comment by bihovi584om** [comment]
بله تست کردم اما هیچ تغییری نکرد،
بدون نصب افزونه پارسی دیت هم به همین صورته چون ساختار ویجت وردپرس کلا از تنظیمات (ساختار تاریخ) دستوری نمیگیره
لطفا بررسی و رفع کنید
مرسی.

**Comment by bihovi584om** [comment]
![Screenshot 2024-03-10 175918](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/a5cbacb2-0ee3-4064-b3a6-eedf1b2b3a4f)

**Comment by hamidrezayazdani** [comment]
If this is the main functionality of WordPress, unfortunately it's not possible for us. We can't create a different widget in the default WordPress widget just to display the date more beautifully. In fact, we have much more important issues than this.
