### ISSUE TITLE
تغییر اندازه فونت {پی} و {فاصله خطوط} نسبت به‌هم برای تجربه کاربری بهتر

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#176]
احساس میکنم 2 تغییر دیگر نیازه
```
    font-size: 14px;
    line-height: normal;
```
یعنی تغییر اندازه فونت p درون ویرایشگر از 13 به حداقل 14px و یکی هم تعریف line-height نرمال هست چون الان خطوط خیلی به هم چسبیده هستن (در ویرایشگر کلاسیک)

_Originally posted by @paulvek in https://github.com/wordpress-parsi/wp-parsidate/issues/168#issuecomment-1987653443_

**Comment by hamidrezayazdani** [comment]
Fixed #180

**Comment by paulvek** [comment]
> Fixed #180

thanks

**Comment by paulvek** [comment]
> Fixed #180

ممنونم. فقط درست نشد و هیچ تغییری نکرد. شما خودتون تست کردید؟
