### ISSUE TITLE
ویجت

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#178]
سلام
قبلتر قسمت ویجت گزارش دادم که کمی جای اصلاح داره اما گفتید اگر از خود وردپرس هست و کارکرد خود وردپرسه ما نمی توانیم تغییر دهیم اما طبق بررسی هایی که دوباره انجام دادم متاسفانه این باگ از افزونه پارسی دیت هست و سایر شمسی سازها این باگ رو ندارند احتمالا در کدهای ویجت پارسی دیت چیزی برعکس ثبت شده

لینک:
https://github.com/wordpress-parsi/wp-parsidate/issues/172

**Comment by bihovi584om** [comment]
مثلا افزونه زیر این شکلی نمایش میده

![Screenshot 2024-03-11 134428](https://github.com/wordpress-parsi/wp-parsidate/assets/130480543/a4ea1e55-e4c2-4a09-a9ba-3c110bb2d5f0)

باز عذرخواهی میکنم بابت ثبت issue و مزاحمتم.
مرسی از شما.

**Comment by man4toman** [comment]
It comes from WordPress translation, it will fix for new version of FA language.
