### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#183]
سلام
پیشنهادی برای پارسی دیت دارم:
با توجه به شرایط اقتصادی فعلی و نبود یک تقویم شمسی مناسب برای وردپرس پیشنهاد میکنم یک راه درآمدزایی برای پارسی دیت در نظر بگیرید و محصولتون رو یا به دوتا دسته (پریمیوم و فیری) ویا به فریمیوم تبدیل کنید.
فرهنگ مشارکت در ایران جا نیوفتاده از طرفی شرایط اقتصادی هم مناسب نیست در نتیجه قوانین دنیای کدباز هم (در این مورد) با توجه به شرایط حال حاضر راهگشای ما نیست! (این موارد برای کشورهایی صدق میکنه که جامعه کاربری مشارکت کننده قوی تری داشته باشند و همچنین شرایط اقتصادی بهتری داشته باشند تا افراد زیادی به مشارکت تمایل پیدا کنند)

**پیشنهادم:**

یک سری قابلیت ها که ضروری و عمومی هست به صورت رایگان برای همه منتشر بشه و ویژگی هایی به صورت فریمیوم یا پریمیوم ارائه بشه؛

مثال فریمیوم میشه با تبلیغ متنی داخل منوی افزونه یا یک ویجت (داخل قسمت داشبورد وردپرس) یا اصلا یه دونه پاپ اپ یا هرچیز دیگه؛
مثال پریمیوم میشه دوتا نسخه منتشر کنید یکی رایگان با ویژگی های عمومی و دیگری پریمیوم با ویژگی های بسیار زیاد و خرید لایسنس؛

قسمت شمسی ساز و تبدیل تاریخ پست ها به شمسی و همچنین تبدیل "ی" و "ک" عربی و در ضمن اعداد به حروف فارسی به صورت رایگان ارائه بشه (به طورکلی تمام قابلیت های فعلی پارسی دیت) اما قابلیتی برای ویرایش اشتباه متن مثل "گرامرلی" (Grammarly) داشته باشه و این قابلیت ها پولی باشه و نیاز به حق اشتراک ماهیانه یا سالانه داشته باشه و همچنین استیکرها و قابلیت های ویژه ای به گوتنبرگ اضافه کنه که همگی این قابلیت ها به صورت پولی ارائه شه
(برای ویرایشگر متن پروزه هایی در گیت هاب موجوده که میتونید بررسی کنید)

یا همچنین در نسخه پولی یا اشتراکی از افزونه هایی مثل گراویتی فرم، المنتور، ACF و .. (یا حتی گزارش های ووکامرس نسخه جدید قسمت واحد پولی و تاریخ های این بخش) پشتیبانی کنه و همچنین در این نسخه در صورت درخواست کاربر، شما از افزونه های جدید هم پشتیبانی کنید مثلا فرض کنید افزونه گراویتی فرم نیاز به تقویم شمسی داشته باشه ولی شمسی ساز شما از اون پشتیبانی نکنه و کاربر به شما درخواست بده و شما در نسخه جدید افزونه تون این پشتیبانی رو اضافه کنید (به نسخه پولی یا اشتراکی تون) و بعدا کم کم به نسخه رایگان هم اضافه کنید.

و شما آروم آروم شروع به اضافه کردن قابلیت جدید به افزونه شمسی ساز می کنید مثلا میتونید مثل افزونه های Shortcodes Ultimate و kadence blocks و یا Ultimate Blocks و... شروع به اضافه کردن قابلیت های جدید به کوتنبرگ کنید این موارد میتونه ارتباطی با تقویم شمسی هم نداشته باشه مثلا میتونه بلوکی به گوتنبرگ برای ایکون شبکه های اجتماعی اضافه کنه یا مثلا Table of Contents به گوتبرگ اضافه کنه یا Social Share و Star Rating وButton و... اضافه کنه.

یه سری ویژگی پیشنهادی:
- لیست TO DO داشته باشه (کارهایی که در اینده قصد انجامش رو داریم) این افزونه و بشه لیستی ساخت تا کارها و وظایفی مشخص کنیم در موعد مقرر بهمون یاداوری کنه
- از ووکامرس پشتیبانی کنه و قسمت گزارش ها و واحد پولی و کل قسمت های جدیش رو تحت پوشش قرار بده، لیست شهر هارو قرار بده، بشه صفحه پرداخت و تسویه حساب رو ویرایش کرد، مشکل اعداد فارسی در کدپستی وکامرس رو حل کنه.
- رویدادهای شمسی  مثل مناسبت ها و تعطیلی ها، ولادت ها و... در داشبورد نمایش بده (یا مثل سایت تایم.آی آر یک جمله از بزرگان رو نمایش بده به صورت رندوم).
- یا استیکر متحرک به گوتنبرگ اضافه کنه (یا استیکرهای خاصی به گوتنبرگ اضافه کنه).
- قابلیت هایی به صفحه ساز المنتور و ویژال کامپوزر اضافه کنه.
- فونت های زیبا و منحصر به فردتری از سایت فونت.آی آر داخل افزونه اضافه کنه تا بشه داخل پیشخوان وردپرس ازشون استفاده کنیم الان پارسی دیت فونت وزیر رو داره که با زدنش فونت پیشخوان میشه وزیر؛ اگه در نسخه پریمیوم کلی فونت دیگه پولی اضافه بشه بسیار جالب و کاربردی تر میشه (برای قسمت فونت پیشنهاد دیگه هم داشتم اما خود وردپرس با کتابخانه فونت به احتمال زیاد پیادش کنه مثلا فونت قالب رو هم در افزونه پریمیوم شما بشه به فونت های پولی فارسی دیگه با یک کلیک تغییرش داد)

و این ویژگی ها به همین شکل پیش میره تا اگه در اینده وردپرس به صورت بومی تقویم شمسی رو اضافه کرد شما بتونید این افزونه رو جداگانه منتشر و برای کاربردهای دیگه، کاربرها رو متقاعد کنید تا بخرند، این ویژگی ها که به اون ها اشاره کردم اگه اضافه بشن حتی در صورتیکه وردپرس به صورت بومی از تاریخ شمسی پشتیبانی کنه بازهم قطعا خریدارانی خواهد داشت (مخصوصا اگر قابلیت های مناسبی به گوتنبرگ، ووکامرس و.. اضافه کنه یا اصلاح و پیشنهاد متن مانند گرامرلی داشته باشه)

مثلا فکر کنید افزونه ای شبیه Grammarly ولی برای وردپرس توسعه بدید که به زبان فارسی متن پیشنهاد بده یا غلط های املایی رو بگیره یا لغت هایی برای ویرایش متن پیشنهاد بده که روز به روز با دیتای کاربرها عملکردش بهتر بشه (حتی در آینده به هوش مصنوعی مجهز بشه) یا اینکه متن رو به زبان دیگری در همونجا ترجمه کنه بدون اینکه نیاز باشه تب مرورگر یا صفحه خاصی رو برای این مورد باز کنیم (مثلا سایت گوگل ترنسلیت رو باز کنیم)

و مورد دیگه نسخه پولی یا اشتراکی دارای پشتیبانی حرفه ای تر و بهتری باشه و در صورت وجود مشکل نیاز به خرید یا تمدید پشتیبانی (لایسنس) باشه؛

اسم این افزونه هم در اینده میتونه اصلا شمسی، هجری و این موارد رو نداشته باشه،
مثلا دستیار وردپرس یا وردپرس اسیستنت (WordPress Assistant) باشه یا هر مورد دیگه که خودتون صلاح می دونید.

صد البته لطفاً ابتدا تعداد درخواست و مسائل مالی و غیر مالی رو به خوبی بررسی کنید تا بفهمید این پروژه به خوبی جوابگو هست، در آینده چه طور؟

مواردی که مطرح کردم مثال هایی بودن شما می تونید موارد بهتر و بیشتری بنا به تجربه تیم تون و بازخورد کاربرها اضافه کنید.

امیدوارم موفق باشید.

**Comment by hamidrezayazdani** [comment]
سلام و وقت بخیر. بسیار ممنونم از مشارکت و پیشنهادات شما.
حقیقتاً من جزء اولین نفرات تیم پارسی‌دیت نبودم. از دو ریلیز اخیر دوستان لطف داشتند و فرصت همکاری دادند و بنده هم در حد توان و زمانم سعی کردم در روند توسعه این افزونه نقشی خیلی کوچیک داشته باشم.
رویکرد و فلسفه اولیه تیم پارسی‌دیت تسهیل کاربری کاربران پارسی زبان وردپرس بوده و بدون هیچ چشمداشتی سالها همین روند ادامه داشته. افراد زیادی خیلی بیشتر و پررنگتر از بنده در این روند کمک کردن.

بهر روی ما اسب زین کرده ای رو سوار شدیم و سعی کردیم که بتونیم بهترین نسخه رو ارائه بدیم منتهی مسئله هم بُعد مالی بوده بعضا و مهمتر از اون دیدگاه نفرات دخیل و اصلی که سعی بر توسعه اوپن سورس داشتند. خیلی از دوستانی که الان وقت میذارن مثل بنده حقیر، خیلی وقته که درآمدمون از توسعه ابزارهای وردپرس نیست و از روی علاقه همچنان در وانفسایی که در ایران شاهدش هستیم دارند کار رو پیش میبرن.

حالا اینکه بشه بعنوان یک منبع درآمدی به پارسی دیت نگاه کرد یک بحثه، بحث توسعه پایدار و مبتنی بر اصول و مستندات یک بحث دیگه. قطعا این مورادی که حضرتعالی به خوبی مطرح کردید و وقت گذاشتید تا با در میون بذارید و حتی فراتر از اون از مدتها پیش گوشه ذهن همه دوستان بوده که بتونیم با انگیزه بیشتری تیم سازی کنیم و کار رو جلو ببریم منتهی عرض کردم، ما اصلا درآمدمون از این فیلد نیست که بخوایم بهش بصورت جدی بپردازیم.
حالا شما در نظر بگیرید که بنده و امثال بنده از اوقات فراغت و خانواده زدم که البته هیچ منتی هم بر دوش کسی ندارم چون علاقه داشتم، منتهی حضرتعالی تشریف میبرید و نه یکی که دو تا کامنت منفی در مخزن وردپرس درج میکنید که «به قولتون عمل کنید». نظر بنده اینه که وقتی همه این سالها بدون هیچ درآمدی این اتفاقها رخ داده و کار پیش رفته، ظاهرا ما ملزم هستیم که برای هر آپدیت مینور وردپرس و ووکامرس در اسرع زمان ریلیز بدیم، وای به حال وقتی که همین روند توسعه در ازای دریافت مبلغی باشه که بنظرم هیچ بخشی از زندگی تیم رو کاور نخواهد کرد.

فرمایشات حضرتعالی متین، ولی وقتی شما که کاملا در روند ایشوهای ریلیز اخیر بودید چنین اقدامی میکنید (احتمالا با تصور اینکه اینجوری از تیم AUTOMATTIC اهرم فشاری بر ما خواهد بود) اجازه بدید که ما اقناع نشیم که این پیشنهاد رو در برنامه حداقل کوتاه مدت یا میان مدت اجرایی کنیم.

بهر روی از پیشنهاد شما و مشارکتی که داشتید و دارید متشکرم.

این نظر بنده حقیر بود، بنده این ایشو رو باز میذارم تا بقیه دوستان هم نظرشون رو اعلام بفرمایند و به نتیجه برسیم.

سپاسگزارم
ارادتمند، حمید رضا یزدانی

**Comment by paulvek** [comment]
سلام آقای یزدانی ما قدردان شما و زحمات شما و تمام افرادی که در این سالها در خلق و توسعه این پلاگین نقش داشتند هستیم.
قطعا مسائل مالی بسیار مهم هستند و شرایط اقتصادی ایران توانی برای کسی نذاشته تا بخواد به صورت رایگان تمام زندگی خودش رو صرف کاری بکنهکسی چنین انتظاری نداره. من که به شخصه چنین انتظاری نداشتم. اما این موضوع رو میشه از جنبه دیگری هم دید.
گاهی اوقات قصد از اطلاع دادن و تیکت و تاپیک جدید ساختن یا هر روش دیگری برای اطلاع رسانی اینه که کار پیش بره و یکسری گیرها رفع شه.
جامعه وردپرس ایران انتخاب های زیادی نداره و همین یک پلاگین در وضعیت استانداردی قرار داشت که الان اوضاع خوبی نداره، واقعا افراد زیادی با همین موضوع مشکلات فراوانی دارن سایت های بزرگ و کوچکی هستند که مشکل دارن
بلاخره زمانی این پلاگین ارائه شده و افراد زیادی اون رو نصب و استفاده کردند. حالا به مشکلات زیادی برخوردند با نسخه های مختلف وردپرس و ووکامرس، با ACF با المنتور و با بسیاری از افزونه و نسخه ها و در شرایط و حالات مختلف، و خیلی از افراد سایت هایی برای دیگران طراحی کردند و مشتریان اونها هم از اونها توقع دارند. واقعا عیب یابی و توسعه یک پلاگین در این حجم کار سخت و پیچیده ایه و حتی بسیاری از برنامه نویس ها هم شاید نتونن به خوبی مشکلاتش رو پیدا کنند و بهترین عیب یابی و بروزرسانی رو توسعه دهندگان اصلی میتونند انجام بدند هرچند این پروژه متن بازه و میشه در اون مشارکت کرد
همین باعث شده حس اضطرار برای این افراد بوجود بیاد و برای سایتهاشون مشکلات فراوانی ایجاد بشه که نه بتونن غیرفعال کنن نه بتونن استفاده از اون رو ادامه بدن
به هر حال از تمامی زحمات شما متشکرم و امیدوارم اونچه خوبه پیش بیاد و اون کاری که درست هست و صلاح میدونید انجام بدید ممنون از لطف بی نهایتتان

**Comment by bihovi584om** [comment]
سلام
خسته نباشید بنده فرمایشات جنابعالی رو خوندم منتها؛
اولا: بنده هیچ وقت برای فشار بر روی شما و انتشار سریع تر اپدیت، هیچ تیکت و بازخورد منفی یا کامنتی در هیچ جا ثبت نکرده و نمیکنم! تنها جایی که برای ارتباط باشما استفاده کردم همین گیت هاب هست. و تنها برای مشارکت، رفع باگ و گزارش مشکل هست تا پروژه سریع تر پیش بره (نه برای جلوگیری از روند توسعه محصول) راستش رو بخوایید حتی یک کامنت هم در مخزن وردپرس برای پارسی دیت ثبت نکردم.

دوما: تو پیشنهاداتم راه های کسب درامد متفاوتی رو گفتم مثلا تبلیغات داخل افزونه و یا ارائه ویژگی هایی که با پرداخت پول باز میشه و قابل استفاده هست (مثلا ویرایش متن و غلط املایی یا فونت های ویژه برای داشبورد وردپرس ) و خیلی پیشنهاد دیگه.
تو این شرایط اقتصادی و فرهنگ سازی ضعیفی که  صورت گرفته چنین پروژه های متن بازی امکان موفقیت بسیار اندکی دارند. برای همین میگم باری کسب درامد این افزونه حتما فکر کنید و راه هایی در نظر بگیرید. حتی اگه جامعه متن باز رو دوست دارید تا زمانی که حداقل شرایط کشور بهتر بشه به این شکل افزونه رو سرپا نگه دارید.


سوما: از تلاش بی مزد و منت شما و دوستانتان در توسعه این افزونه واقعا سپاس گزارم و تشکر میکنم.

چهارما: با توجه به گفته های شما کاملا توجیه شدم شرایط اقتصادی بسیار بده و کسب درامد از پارسی دیت هزینه های تیم حرفه ای رو توجیه نمیکنه در همین راستا پیشنهاد میکنم تیمی برای این منظور ایجاد کنید که مثلا هفته ای چند ساعت (از یک روزشون) رو به توسعه این افزونه اختصاص بدن، این شکلی بسیار بهتر از اینه که به صورت دائم بر روی توسعه این افزونه کار کنند چون با توجه به گفته شما درامد پارسی دیت هزینه این تیم رو کاور نمیکنه منظورم اینه تیم شما به صورت پاره وقت و کم وقت بزارن برای توسعه این افزونه و اما راه هایی برای کسب درامد همین وقت اندک که می گذارید در نظر بگیرید  تا احساس نکنند وقتشون تلف میشه همچنین دلخوشی هرچه اندک داشته باشند.

حقیقتا چند وقت پیش قصد داشتم محصولی از یک فروشگاه اینترنتی خریداری کنم دیدم زمان تحویل مرسوله کاملا میلادیه ببینید کار به کجا رسیده که سایت هایی کلا قید شمسی بودن سایت/فروشگاهشون رو زدن و زمان سایتشون کلا میلادی شده. البته این یک مورده من موارد بسیار بیشتری از این دست رو دیدم لازم به ذکره که بنده این مشکل رو از سمت شما نمیدونم و شرایط به گونه ای رقم خورده که چنین اتفاقاتی رخ داده.
 از تلاش های شما ممنونم و لذا با همین تلاش های شماست که چیزی تحت عنوان وردپرس فارسی داریم.

باز هرطور که شما و تیم تون صلاح میدونید و بررسی می کنید رو بهترین در نظر میگیریم.


و اما بازهم از تلاش شما و تمام افراد دیگه در توسعه افزونه و کلا وردپرس فارسی تشکر و قدر دانی میکنم.
