### ISSUE TITLE
not compatible with WordPress 6.5x and WooCommerce 8.7x

### ISSUE THREAD

**Issue by paulvek** [wordpress-parsi/wp-parsidate#184]
Hello. Now it's time to do what you've been promising for a long time and what users need.
Please go for updating and compatibility with WordPress 6.5x and WooCommerce 8.7x

**Comment by 79ho3ein** [comment]
Hi @man4toman, Is the development of this plugin stopped?

**Comment by man4toman** [comment]
Parsidate is a free and open source plugin, and there is no business plan for it.
If you are a developer and can help to boost the development, feel free to do it in github, otherwise, please wait for complete test and release new version.

Regards

@paulvek @79ho3ein
