### ISSUE TITLE
تغییر تاریخ در تگ های متا

### ISSUE THREAD

**Issue by ehsanfotoo** [wordpress-parsi/wp-parsidate#185]
سلام وقت بخیر
لطفاً در تنظیمات پلایگن ، گزینه‌ای اضاف کنین که تاریخ‌ها در متا تگ‌ها را به میلادی بنویسید و نوع نوشتنشان نیز فارسی نباشد.

`<meta property="article:published_time" content="۱۴۰۰-۰۸-۱۵\۰۴:۵۸:۰۰" />`
`<meta property="article:modified_time" content="۱۴۰۳-۰۲-۰۲\۲۰:۳۹:۳۶" />`

همچنین انتخاب ساعت را به صورت Range ساختید که انتخاب ساعت را بسیار سخت کرده. لطفاً استایلش را تغییر بدید.
![Time](https://github.com/wordpress-parsi/wp-parsidate/assets/9595483/086e3625-3a3c-4274-9695-44c67c411329)

**Comment by man4toman** [comment]
Fixed In update
