### ISSUE TITLE
Issue with "wp-persiandate" Plugin: Sitemap Date Modification

### ISSUE THREAD

**Issue by ghost** [wordpress-parsi/wp-parsidate#188]
Firstly, I would like to express my appreciation for developing the "wp-persiandate" plugin. It has undoubtedly enhanced the functionality of WordPress for Persian language users.
However, I have encountered an issue regarding the modification of the updated date in the WordPress sitemap by the plugin. As you may know, the sitemap serves as an external page within WordPress, and your plugin seems to alter its date just like other pages. This alteration has inadvertently caused a problem within the sitemap when inspected through Google Search Console.
To address this issue and ensure the proper indexing of our website's pages, I suggest implementing a solution that excludes the conversion of dates specifically within the sitemap routes. By doing so, we can prevent any further complications arising from the date modifications.
Thank you for your attention to this matter.

**Comment by man4toman** [comment]
Fixed [here](https://github.com/wordpress-parsi/wp-parsidate/commit/8647a2888b224dd98cea2e52ccba95a387d82bb9)

**Comment by ghost** [comment]
@man4toman thanks a lot
