### ISSUE TITLE
مشکل عدم وجود ماه فروردین در قسمت ویرایش سریع محصول و ویرایش محصول ووکامرس

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [wordpress-parsi/wp-parsidate#193]
همانطور که در اسکرین شات ها مشاهده میکنید ماه فروردین در قسمت ویرایش سریع محصولات ووکامرس و همچنین صفحه ویرایش محصول وجود ندارد.
![2024-07-26_185235](https://github.com/user-attachments/assets/6081734d-14b9-4f6f-aa2b-3d20ab84eb30)
![2024-07-26_185711](https://github.com/user-attachments/assets/94fcd3f7-0ba8-4467-8cfc-e962732caaf4)

**Comment by man4toman** [comment]
Fixed [here](https://github.com/wordpress-parsi/wp-parsidate/commit/81c522d590056f29088faa959278626d6750742c).
