### ISSUE TITLE
مشکل فرمت تاریج و درج اشتباه تاریخ در قسمت سفارشات ووکامرس

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [wordpress-parsi/wp-parsidate#194]
![2024-07-27_110414](https://github.com/user-attachments/assets/66ac7be0-b177-44b9-81ff-038bd2ed0be1)
بعد از این که سفارشی رو بصورت دستی ایجاد میکنیم، در هنگام بروزرسانی وضعیت سفارش خطای فرمت تاریخ ایجاد میشه و حتی با انتخاب تاریخ از روی data picker مشکل رفع نمی‌شود و همچنان میگه تاریخ رو به شکل صحیح وارد کن و اجازه بروزرسانی وضعیت سفارش رو نمیده.

**Comment by amirhoseinsadeghi** [comment]
![image](https://github.com/user-attachments/assets/d7a99531-9f5d-4418-8c5d-7349c68a2c6f)
این هم از نمایش اشتباه تاریخ در قسمت سفارشات ووکامرس (سال 782)

**Comment by mehrshaddarzi** [comment]
See:
https://github.com/wordpress-parsi/wp-parsidate/pull/191

**Comment by man4toman** [comment]
Fixed at #191
