### ISSUE TITLE
پیشنهاد هماهنگی با المنتور + دیت پیکر

### ISSUE THREAD

**Issue by hossin0241** [wordpress-parsi/wp-parsidate#196]
لطفا با المنتور هماهنگ بشه
و
دیت پیکر هم شمسی بشه
ممنون

**Comment by man4toman** [comment]
سلام @hossin0241 
مشکل المنتور چی هست؟ چه بخشی نیاز به هماهنگی داره؟
توجه کنید که دیت‌پیکر فقط جنبه شمسی کردنش مهم نیست و ممکنه در بخش‌های زیادی ازش استفاده بشه و به همین جهت بجز در موارد خاص، در افزونه‌های دیگه این مورد رو با افزونه پارسی‌دیت شمسی نمی‌کنیم.

**Comment by man4toman** [comment]
با توجه به اینکه پاسخی دریافت نکردیم و بخشهای متفاوت دیگری که از اهمیت بیشتری برخوردارن رو در روند کار داریم، این ایشو رو میبندم تا در آینده چنانچه فرصت شد بررسی کنیم.

**Comment by hamidrezayazdani** [comment]
Added #226
