### ISSUE TITLE
Problem with is_feed

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#197]
در بررسی سایت با کوئری مانتیتور به این خطا رسیدم. در قسمت مدیریت هم دیده میشه.

Function is_feed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. (This message was added in version 3.1.0.)

```
Caller
is_feed()
wp-includes/query.php:417
wpp_is_feed()
wp-content/plugins/wp-parsidate/includes/general.php:119
disable_wpp()
wp-content/plugins/wp-parsidate/includes/plugins/disable.php:28
wpp_fix_i18n()
wp-content/plugins/wp-parsidate/includes/fixes-dates.php:164
apply_filters('wp_date')
wp-includes/plugin.php:205
wp_date()
wp-includes/functions.php:314
date_i18n()
wp-includes/functions.php:201
rocket_init()
wp-content/plugins/wp-rocket/inc/main.php:37
do_action('plugins_loaded')
wp-includes/plugin.php:517
```

**Comment by man4toman** [comment]
[Fixed](https://github.com/wordpress-parsi/wp-parsidate/commit/9ba018704327a5db99407aa7a4fc73e3d9b1050e).
