### ISSUE TITLE
مشکل گزینه های اعتبارسنجی کد پستی و شماره تماس 

### ISSUE THREAD

**Issue by hadiomid** [wordpress-parsi/wp-parsidate#198]
سلام وقت بخیر
در نسخه جدید موارد زیر وجود داره:

گزینه های اعتبارسنجی کد پستی و شماره تماس رو فعال کردم. اما کد پستی اگر معتبر باشه یا نامعتبر، در هر صورت پیغام زیر رو نمایش میده
کدپستی / ZIP ارائه‌شده نامعتبر است
شماره تماس رو هم در صورت معتبر میشناسه
گزینه "نمایش شهرها به‌صورت لیست کشویی" هم هیچ تغییری ایجاد نمیکنه. (این مشکل فقط در صفحه پرداخت قسمت ویرایش آدرس وجود داره و در صفحه ویرایش اطلاعات کاربری درست کار میکنه)

**Comment by hamidrezayazdani** [comment]
Fixed in https://github.com/wordpress-parsi/wp-parsidate/commit/93094424dc5a6a9e44ab8ba63915278a9a0277bf

سلام وقت بخیر. در مورد لیست شهرها، با پوسته استورفرانت و آخرین نسخه ووکامرس تست شد و در هر دو بخش روند پرداخت و هم بخش آدرسها به درستی کار میکنه، آیا شما از افزونه ای برای مدیریت فیلدهای پرداخت ووکامرس استفاده میکنید؟

**Comment by hadiomid** [comment]
سلام، وقت بخیر
برای مدیریت فیلدها پلاگینی استفاده نمیکنم.
آخرین نسخه ووکامرس و وردپرس نصب هست.
پوسته hello elementor و پلاگین های زیر نصب و فعال هست
filter everything
elementor
rank math
perfmatters

**Comment by hamidrezayazdani** [comment]
سلام مجدد، ممنون از پاسخ شما. من با شرایط زیر نتونستم مشکلی پیدا کنم:
WordPress: 6.6.2
WooCommerce: 9.3.3
Elementor: 3.24.5
Hello elementor: 3.1.1
Rank Math SEO: 1.0.229
Filter Everything: 1.8.6
Perfmatters: 2.3.1

احتمالا یا با افزونه دیگه یا بلاک کدی این مشکل براتون پیش میاد، لطفا در صورت امکان همه افزونه ها رو غیر فعال کنید و استورفرانت رو فعال و تست کنید و نتیجه رو اطلاع بدید.

**Comment by hadiomid** [comment]
همه پلاگین ها بجز ووکامرس و پارسی دیت رو غیرفعال کردم. با پوسته های استور فرانت و ۲۰۲۴ هم تست کردم، تفاوتی نداشت.

<img width="245" alt="Screenshot 2024-10-08 at 12 36 35 PM" src="https://github.com/user-attachments/assets/7b329d1b-5ad8-442b-95fa-8644b491dd79">

**Comment by hamidrezayazdani** [comment]
سپاس، متاسفانه من نمیتونم این حالت رو شبیه سازی کنم و برای خودموبا مواردی که در کامنت قبل کفتم به درستی کار میکنه. ووکامرس فارسی رو نصب ندارید؟
