### ISSUE TITLE
مشکل لود فونت وزیر

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#199]
در قسمت مدیریت وردپرس

https://*.ir/wp-content/plugins/wp-parsidate/assets/fonts/Vazir-Regular.woff2 net::ERR_ABORTED 404 (Not Found)
https://*.ir/wp-content/plugins/wp-parsidate/assets/fonts/Vazir-Bold.woff2 net::ERR_ABORTED 404 (Not Found)

**Comment by man4toman** [comment]
Fiexd ad [here](https://github.com/wordpress-parsi/wp-parsidate/commit/b13b82212efc8053b931a28026116dcb81cb5cbd)
