### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#200]
PHP Warning:  Attempt to read property "ID" on int in /var/www/*.ir/htdocs/wp-content/plugins/wp-parsidate/includes/fixes-dates.php on line 171

**Comment by callmeahmedr** [comment]
Try updating the line `171` in `wp-parsidate/includes/fixes-dates.php` to this:

`$post_id = (is_object($post) && isset($post->ID)) ? $post->ID : null;`

This change adds a check to ensure `$post` is an object before accessing its `ID` property. If `$post` is not an object, `$post_id` will be set to null, avoiding the warning.

**Comment by man4toman** [comment]
Fixed at #201
