### ISSUE TITLE
وجود همزمان 2 گزینه زمان و تاریخ انتشار در صفحه ویرایش نوشته گوتنبرگ

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [wordpress-parsi/wp-parsidate#202]
در قسمت **ویرایش نوشته گوتنبرگ** ما **همزمان 2 گزینه انتشار** داریم:
![2024-08-24_084420](https://github.com/user-attachments/assets/20c77e40-026e-490d-bac4-7175b8fb4682)

**Comment by hamidrezayazdani** [comment]
Fixed in WP 6.6.2 https://github.com/wordpress-parsi/wp-parsidate/commit/93094424dc5a6a9e44ab8ba63915278a9a0277bf

**Comment by hamidrezayazdani** [comment]
Fixed in WordPress from version 6.1 to 6.6.2 https://github.com/wordpress-parsi/wp-parsidate/commit/a8b52a606437a05d21d8c2ab7e0d40e0c6506ba6

**Comment by amirhoseinsadeghi** [comment]
من از آخرین نسخه وردپرس (6.6.2) استفاده میکنم و مشکل همچنان پابرجا است و با تغییرات در نسخه تحت توسعه پارسی دیت هنوز مشکل حل نشده است و همچنان دو گزینه انتشار در گوتنبرگ برگه ها و غیره وجود دارد.
![image](https://github.com/user-attachments/assets/381f8f23-d121-4939-ab2e-fbd6df504dd6)

**Comment by hamidrezayazdani** [comment]
لطفا کش مرورگر رو خالی کنید. چون تغییر ورژن روی فایلهای مربوطه انجام نشده مرورگر نسخه کش شده رو لود میکنه. یا میتونید با pruvate mide در فایرفاکس یا incognito در کروم هم تست کنید
