### ISSUE TITLE
حل نشدن مشکل تاریخ در متاتگ

### ISSUE THREAD

**Issue by ehsanfotoo** [wordpress-parsi/wp-parsidate#203]
سلام
در #185 مشکل نمایش تاریخ در متا تگ را بیان کردم.

`<meta property="article:published_time" content="۱۴۰۳-۰۴-۲۵\۰۸:۴۲:۲۶" />`
`<meta property="article:modified_time" content="۱۴۰۳-۰۴-۲۵\۰۸:۴۲:۲۹" />`

الان روی اینها تست کردم اما همچنان مشکل وجود دارد:
- نسخه 5.1.0 wp parsidate
- وردپرس 6.6.2
- قالب دو هزار و بیست و چهار 1.2
- رنک مث رایگان 1.0.227.1
- رنک مث پرمیوم 1.0.69

در تنظیمات پلاگین وقتی با فعال‌کردن گزینه "تاریخ‌ها به صورت تاریخ خورشیدی (جلالی) درمی‌آیند" را غیرفعال میکنم مشکل حل میشود اما همه تاریخها میلادی میشوند.

**Comment by man4toman** [comment]
سلام
با آخرین آپدیت از گیتهاب تست کردید؟

**Comment by ehsanfotoo** [comment]
> سلام با آخرین آپدیت از گیتهاب تست کردید؟

بله. دیروز دانلود و تست کردم.

**Comment by man4toman** [comment]
روی آخرین نسخه تست شد و خروجی به درستی داره نمایش داده میشه.

![image](https://github.com/user-attachments/assets/aa6be0c2-1868-4af2-964d-a3b21f74917c)

```
<!-- بهینه‌سازی موتور جستجو توسط Rank Math PRO - https://rankmath.com/ -->
<meta property="og:updated_time" content="2023-05-17T19:17:09+03:30" />
<meta property="article:published_time" content="2023-05-16T23:43:34+00:00" />
<meta property="article:modified_time" content="2023-05-17T15:47:09+00:00" />
```

**Comment by ehsanfotoo** [comment]
برای صفحه اصلی و برگه‌ها این مشکل وجود ندارد. فقط برای نوشته‌ها این مشکل وجود دارد.
روی دو سایت مختلف تست کردم. هر دوتاشون همین مشکل را داشتند.

**Comment by man4toman** [comment]
اگر امکان ارسال دسترسی موقت برای بررسی مشکل رو دارید لطفا برای من دسترسی ایجاد کنین.
چون نمیتونم مشکل رو روی سایت‌هایی که دارم ببینم و خروجیشون درست هست.

**Comment by ehsanfotoo** [comment]
از کجا دسترسی را براتون ارسال کنم؟  اینجا امن نیست.

**Comment by man4toman** [comment]
لطفا به ایمیل man4toman@gmail ارسال کنین.

**Comment by ehsanfotoo** [comment]
ایمیل کردم. لطفاً بررسی کنید.
