### ISSUE TITLE
vazir font styles conflicts with dashicon font family

### ISSUE THREAD

**Issue by Abdipour** [wordpress-parsi/wp-parsidate#204]
Hi
If we activate the Vazir font, in the wp-parsidate/assets/css/vazir-font.css file, line 33 has this rule:
`.rtl .edit-post-visual-editor *`
This overwrites the Dashicons rule at line 67:

```
.dashicons, .dashicons-before::before, .wpseo-metabox-menu ul li span.dashicons::before {
	font-family: dashicons;
}
```

This causes the Dashicons to break in the post editor.

![image](https://github.com/user-attachments/assets/19d60206-c60d-4951-8286-566425c1b762)

**Comment by man4toman** [comment]
Hi @Abdipour 
Did you check it with latest version of plugin?

**Comment by Abdipour** [comment]
> Hi @Abdipour Did you check it with latest version of plugin?

Yes, wp-parsidate v5.1.0 with WP v6.6.2

**Comment by man4toman** [comment]
I can't reproduce the problem and the icons shows well, but I added a small change, please check it again.
@Abdipour

**Comment by Abdipour** [comment]
The Dashicons in the post editor only include the "link" icon, as shown in the screenshot below.

![image](https://github.com/user-attachments/assets/f19b1584-ca4c-462f-8fce-ccf027cf86c0)

Additionally, if you create a custom block that uses Dashicons for its icon, you will encounter the same issue.

Anyway, the problem was fixed with your change.
Thank you.
