### ISSUE TITLE
Payment Gateway Options Not Saved

### ISSUE THREAD

**Issue by mehrshaddarzi** [wordpress-parsi/wp-parsidate#206]
MutiCheckBox Options not saved when user want to disbale all options:

https://github.com/user-attachments/assets/8800333b-b31e-4d08-9855-034df9e57d3f

**Comment by man4toman** [comment]
Thanks @mehrshaddarzi 
[Fixed](https://github.com/wordpress-parsi/wp-parsidate/commit/9159dcd335c39bcd0144f616900787c639d563a9)

**Comment by amirhoseinsadeghi** [comment]
> Thanks @mehrshaddarzi [Fixed](https://github.com/wordpress-parsi/wp-parsidate/commit/9159dcd335c39bcd0144f616900787c639d563a9)

من آخرین تغییرات افزونه رو دانلود و نصب کردم اما همچنان این مشکل حل نشده و وقتی همه درگاه‌های پرداخت رو غیر فعال و در نهایت ذخیره میکنیم، باز هم مجددا خودشون فعال هستند و مشکل باقیه!

![2024-10-07_214203](https://github.com/user-attachments/assets/13d1d512-7e93-426d-8188-ceab369a67e3)

**Comment by man4toman** [comment]
@amirhoseinsadeghi 
لطفا دوباره تست کنین.

**Comment by amirhoseinsadeghi** [comment]
جزئیات خطا
===================
یک خطا از نوع E_ERROR در خط 459 از پرونده //wp-content/plugins/wp-parsidate/includes/settings.php رخ داد. پیام خطا: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, int given in /wp-content/plugins/wp-parsidate/includes/settings.php:459
Stack trace:
#0 public_html/wp-content/plugins/wp-parsidate/includes/settings.php(459): in_array()
#1 public_html/wp-admin/includes/template.php(1836): wpp_multicheck_callback()
#2 public_html/wp-content/plugins/wp-parsidate/includes/settings.php(686): do_settings_fields()
#3 public_html/wp-includes/class-wp-hook.php(324): wpp_render_settings()
#4 public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 public_html/wp-admin/admin.php(259): do_action()
#7 {main}
  thrown

![2024-10-12_163832](https://github.com/user-attachments/assets/73994d49-7e13-445d-bcd2-1f4951864211)
