### ISSUE TITLE
مستندات توابع برای استفاده در دیگر پلاگین ها

### ISSUE THREAD

**Issue by jaavid** [wordpress-parsi/wp-parsidate#210]
من دارم یک پلاگین اختصاصی برای پروژه خودم مینویسم که نیاز دارم بعضی جاها تاریخ رو تبدیل کنم
از این پلاگین و توابع ش استفاده میکنم

جایی مستنداتی برای توابع دارید؟
اگه دارید من میتونم در بهبود و تکمیلش کمک کنم

**Comment by man4toman** [comment]
سلام وقت بخیر این بخش رو بررسی  کنین:

https://wp-parsi.com/docs/

به زودی بخش مستندات رو تکمیل‌تر و بهبود میدیم.
اگر هم میتونید توی این مورد کمک کنید ممنون میشم اطلاع بدید.

**Comment by jaavid** [comment]
بله حتما، هر کمکی از دستم بربیاد خوشحال میشم انجام بدم
