### ISSUE TITLE
Shamsi Date is not working!

### ISSUE THREAD

**Issue by Siaavash** [wordpress-parsi/wp-parsidate#211]
WordPress database error FUNCTION ***.count does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual for query 
				SELECT date ( post_date ) AS date, 
				  	count ( ID ) AS count
				FROM wp_posts
				WHERE post_date < NOW()
					AND post_type = 'post'
					AND post_status = 'publish'
				GROUP BY date
				ORDER BY post_date DESC
				 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/less-reloaded-child/index.php'), wp_get_parchives
 WordPress database error FUNCTION ***.count does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual for query 
				SELECT date ( post_date ) AS date, 
				  	count ( ID ) AS count
				FROM wp_posts
				WHERE post_date < NOW()
					AND post_type = 'post'
					AND post_status = 'publish'
				GROUP BY date
				ORDER BY post_date DESC
				 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/less-reloaded-child/index.php'), wp_get_parchives

**Comment by man4toman** [comment]
Hi @Siaavash 
Please go to `includes/fixes-archives.php`, at line **129** and change it to this:
`count( ID ) AS count`

And let me know if the problem resolved or not.
