### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#215]
- [x] Translation not loaded
- [x] Option for dashboard widget
- [x] Setup track-able widget links

**Comment by hamidrezayazdani** [comment]
Regarding the third case, it is enough to make the links UTM if you mean the three bottom links in the widget.
But if you mean the sponsor section, we should use link-shortening services. We put the sponsoring link (which is usually UTM) in the link shortener and the shortened link in the sponsorship section of WP Planet.

**Comment by hamidrezayazdani** [comment]
Fixed loading translations #219

**Comment by hamidrezayazdani** [comment]
Fixed "Option for dashboard widget": #220

**Comment by hamidrezayazdani** [comment]
Since two tasks have been completed and the decision regarding the third task has been made in the Parsidate developer group, I'm closing this issue.
