### ISSUE TITLE
مشکل آیکون پارسی دیت

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#216]
سلام
نسخه اخر یعنی 5.1.1 در قسمت انتخابگر تاریخ (سال) آیکونش به درستی نمایش داده نمیشه اولش که من فکر کردم کلا نمیشه تاریخ رو غیر از اون لیست چیز دیگه داد :)

ایکون تغییر تاریخ (سال) پارسی دیت
![311511022-819a1f53-fab0-45db-aa01-2fef85e976ba](https://github.com/user-attachments/assets/9233ad3a-e7ca-47bc-8d4e-064e8ba70b08)
در حال حاضر به شکل بالا نمایش داده میشه

اما باید به شکل زیر نمایش داده بشه:
![311668986-0a5fa903-b082-4a56-ab82-81e8c8f1338a](https://github.com/user-attachments/assets/04dae39f-d26a-4345-8174-5b9b45e5e9df)

روی چندتا سایت تست کردم تمام افزونه هارو غیر فعال کردم کش مرورگر رو هم پاک کردم باز مشکل نمایش فلش های انتخابگر تاریخ (سال) پارسی دیت حل نشد.
خودتون میتونید روی یه سایت جدید نصب کنید و تست کنید یا در صورت نیاز بگید لینک ورود بدم بررسی کنید:

**Comment by hamidrezayazdani** [comment]
با سلام، سپاسگزاریم بابت مشارکت و همراهی شما. این مورد رو بنده بررسی میکنم و به زودی در نسخه بعدی مشکل حل میشه.

از اینکه به بهبود پارسی دیت کمک میکنید ممنونم. 🙏🏽

**Comment by hamidrezayazdani** [comment]
Fixed #219
