### ISSUE TITLE
مشکل در تاریخ انتشار پست ها و برگه ها

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#217]
سلام
نمیدونم دقیق اسم این باگ رو چی بزارم اما وقتی پست یا برگه ای نوشته باشیم و قصد انتشار داشته باشیم وقتی پارسی دیت روشنه زمان انتشار پست رو در (ساعت انتشار پست) اشتباه نمایش میده به عکس های زیر توجه کنید:
ساعت انتشار پست وقتی پارسی دیت روشنه:
![Screenshot 2024-11-09 055047](https://github.com/user-attachments/assets/358d338a-85a8-4514-af19-c6047ef4ae92)

ساعت انتشار پست وقتی پارسی دیت خاموشه:
![Screenshot 2024-11-09 055414](https://github.com/user-attachments/assets/e2dbbde7-9158-4037-bb6a-57b66d801a63)

میبینید که الان ساعت 05:53 هست اما پارسی دیت به اشتباه اون رو 02:19 در نظر گرفته
تنها زمانی درست نمایش میده که روی گزینه انتشار بزنی و اکنون رو بزنی وگرنه ساعت انتشار رو اشتباه نمایش میده
حالا نمیدونم این اشتباه فقط نمایشی هست یا ساعت انتشار پست رو هم اشتباه انجام میده
ممنون.

**Comment by bihovi584om** [comment]
ضمنا منطقه زمانی و ساعت و تاریخ وردپرس بنده از تنظیمات به درستی تنظیمه. (زمان محلی)

و بررسی مجددی که انجام دادم پارسی دیت ساعت انتشار رو هم اشتباهی انجام میده و با ساعت دقیق ما اختلاف داره
تا جایی که مطلع شدم و بررسی کردم پارسی ساعت انتشار پست رو از ساعت جهانی فراخوانی میکنه نه از ساعت تهران.

ساعت جهانی 1403-08-19 02:19:12 است. زمان محلی 1403-08-19 05:53:12 است. 
این جمله رو تو تنظیمات وردپرس دیدم و مطمئن شدم که باگی در پارسی دیت وجود داره که زمان انتشار پست ها رو از از زمان جهانی برمیداره و از منطقه زمانی تهران (که ما تنظیم میکنیم) این کار صورت نمیگیره

ممنون.

**Comment by hamidrezayazdani** [comment]
Fixed: #220

**Comment by ali110309** [comment]
سلام وقت بخیر
ظاهرا این مشکل همچنان وجود داره و در ویرایشگر گوتنبرگ به جای  تاریخ و ساعت امروز (بی درنگ) تاریخ مربوط به 9 ماه قبل نمایش داده می شود و این باعث می شود که هنگام انتشار پست، تاریخ انتشار هم اشتباه درج شود و همیشه باید به صورت دستی تاریخ امروز را تنظیم کنیم.
من در حال حاضر از وردپرس نسخه 6.7.1 و پلاگین نسخه 5.1.2 استفاده میکنم 
لطفا این مورد رو بررسی کنید.
