### ISSUE TITLE
نمایش تاریخ امروز به جای تاریخ ایجاد پست در قسمت وبلاگ

### ISSUE THREAD

**Issue by 3ehrouz** [wordpress-parsi/wp-parsidate#224]
در قسمت /blog وبسایت تاریخ همه پستارو به جای تاریخ ایجاد پست تاریخ امروز رو نشون میده و هر روز هم آپدیت میشه
تو صفحه خود پست مشکلی نداره

![4  Blog Carts only show today date instead of publish date](https://github.com/user-attachments/assets/70da5e3d-18e8-4053-bfbb-9cae506e0762)

**Comment by 3ehrouz** [comment]
اشکال از قالب نیست و وقتی با افزونه تاریخ رو شمسی میکنم، این مشکل بوجود میاد

**Comment by bihovi584om** [comment]
بله بنده هم این مشکل رو دارم

این هم لینک برای اینکه این مشکل رو بهتر بررسی کنید:

https://themes.wpmonster.co/Enfold/new/medical/news/

مقالات صفحه بالا در تاریخ 25 تیر 1395 منتشر نشدن بلکه صفحه ای که اون مقالات در اونها نمایش داده میشن در اون تاریخ منتشر شده

مثلا داخل یک از اون مقاله ها بریم میبینیم که تاریخ انتشارش چیز دیگری هستش
مثلا این مقاله:
https://themes.wpmonster.co/Enfold/new/medical/a-small-gallery/

در 5 بهمن 1391 منتشر شده اما پارسی دیت در اون صفحه (بالا) که لیست مقالات رو نمایش میداد تاریخ رو میزنه 25 تیر 1395

لطفا مشکل افزونه رو اصلاح کنید.

**Comment by man4toman** [comment]
سلام ممنونم بابت گزارش مشکل
اسم پوسته‌هایی که استفاده می‌کنید رو لطفا بگید
@3ehrouz @bihovi584om

**Comment by 3ehrouz** [comment]
سلام
موبکس
من از تم فارست خرید کردم تو وبسایت‌های ایرانی نیست
https://themeforest.net/item/mobex-auto-parts-wordpress-theme/49859756
اینم وبسایت خودم
https://www.motoyadak.com/blog/

**Comment by bihovi584om** [comment]
سلام قالب انفولد
Enfold

**Comment by bihovi584om** [comment]
همچنین میتونم دسترسی جهت بررسی و تست خدمت تون بدم
ممنون.

**Comment by hamidrezayazdani** [comment]
Fixed https://github.com/wordpress-parsi/wp-parsidate/commit/6d19832d6ee5d851c1652faf2fc75931c9242306

**Comment by 3ehrouz** [comment]
نصب کردم مشکل برطرف نشد متاسفانه
