### ISSUE TITLE
Too many errors after activating latest version in WP 5.1

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#24]
I'm testing the latest version of WP Parsidate with latest version of Wordpress on my local machine. After activating the plugin i get a lot of errors on front-end pages. From home page to single pages and categories.

It seems to be one error but it exists in every query and more. here is the error:

`Notice: _usort_terms_by_ID is <strong>deprecated</strong> since version 4.7.0! Use wp_list_sort() instead. in ..:\wamp64\www\...\wp-includes\functions.php on line 4329`

**Comment by man4toman** [comment]
Hi @majiix 
Thanks, we'll fix this issue asap.

**Comment by man4toman** [comment]
@lord-viper 
We must update our permalink function based on the latest update:
`https://github.com/WordPress/WordPress/blob/master/wp-includes/link-template.php#L119`

**Comment by man4toman** [comment]
This issue has been resolved based on PR #27

**Comment by man4toman** [comment]
#
