### ISSUE TITLE
Bad UX for the date picker

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#31]
Hi,
With all the compatibility of the new version with Gutenberg, there's a really bad UX issue with the date picker of post. The range sliders for selecting time doesn't really have good UX. When you select it, it jumps to the current time and not just once, but every time that i open the date picker. It would be so much better if it was like the default Wordpress time picker. Just a simple number input is really better than range slider. Range slider is really annoying.
Please consider this in the next version.

**Comment by man4toman** [comment]
Hi @majiix 
We will consider your idea and will work on it.

**Comment by man4toman** [comment]
Hi @majiix
Thanks, we will consider your idea and will work on it.

Regards

**Comment by hamidrezayazdani** [comment]
Duplicated issue #35
