### ISSUE TITLE
Error while save ACF fields

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#32]
Hi,
When i try to save advanced custom fields "**Field Groups**" i get these errors:

`Notice: Undefined offset: 0 in ...\wp-content\plugins\wp-parsidate\includes\fixes-permalinks.php on line 246`
`Notice: Undefined offset: 1 in ...\wp-content\plugins\wp-parsidate\includes\fixes-permalinks.php on line 247`
`Notice: Undefined offset: 2 in ...\wp-content\plugins\wp-parsidate\includes\fixes-permalinks.php on line 248`
`Warning: Cannot modify header information - headers already sent by (output started at ...\wp-content\plugins\wp-parsidate\includes\fixes-permalinks.php:246) in ...\wp-includes\pluggable.php on line 1251`
`Warning: Cannot modify header information - headers already sent by (output started at ...\wp-content\plugins\wp-parsidate\includes\fixes-permalinks.php:246) in ...\wp-includes\pluggable.php on line 1254`

**Comment by man4toman** [comment]
Hi @majiix 
Which package did returns these errors?
ACF free version or pro version?

**Comment by majiix** [comment]
@man4toman  It's ACF Pro.
And it's not nulled version.

**Comment by alireza-s13** [comment]
اصلاح شد : 
این مشکل مربوط به اون افزونه نیست. این طور که متوجه شدم کلا نسخه 3.0.1 با نسخه 4.9.10 وردپرس مشکل داره.

**Comment by par6n** [comment]
Closing as it seems it's resolved.
