### ISSUE TITLE
Bug in permalink structure with date conversion

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#33]
Hi,
Suppose this is permalink structure of you WP: `/%category%/%postname%/`
The permalink on front-end should be like this: `https://abc.com/arts-and-culture/cinema/interstellar/`
Now if you activate "**Convert date in permalinks**" either on purpose or by mistake, the permalink on front-end will change to this with just one category and no subcategory and an extra slash in URL:
`https://abc.com/arts-and-culture//interstellar/`
Whatever the permalink structure is, i think Parsidate should only convert the dates in permalinks and should not change the structure, even if the user activate that option.

**Comment by man4toman** [comment]
Hi @majiix 
Thanks for report this issue.

In older versions of WordPress, if we want to convert the permalink date, we have to do something on it.
I think it comes from there.

We'll work on it.

**Comment by amirhp-com** [comment]
Hi @majiix . I was trying to reproduce the mentioned issue above and I couldn't! Maybe it's not an issue anymore and we should close this thread. If you are still having problem using this feature please share with us steps to reproduce the problem.
