### ISSUE TITLE
post/page return 404 if post/page and attachment have the same slug

### ISSUE THREAD

**Issue by KamranKhorsandi** [wordpress-parsi/wp-parsidate#34]

**Comment by man4toman** [comment]
Hi @KamranKhorsandi 
Thanks for you pr!
Would you please share more information about this issue?

**Comment by KamranKhorsandi** [comment]
@man4toman 
Occasionally, in certain circumstances, the name of the post and attachment may be the same.
For example moving the old site database to the new site manually. Or import data by php code into db.
In this case, this cause a 404 error.

**Comment by par6n** [comment]
Is this fixed now? @KamranKhorsandi @man4toman

**Comment by man4toman** [comment]
I'm not sure about this, maybe this cause problems in attachment's permalink.
This is standard query for permalinks based on WordPress, I think data migration is on user and it's better they care about that.

I suggest to tole back this change.
What is you thought?
