### ISSUE TITLE
Range slider not working fine in WP 5.2

### ISSUE THREAD

**Issue by majiix** [wordpress-parsi/wp-parsidate#35]
Hi
Range slider for selecting time is not working fine in 5.2. By moving the handle to right, it goes to left and vice versa.
Please fix this.

**Comment by man4toman** [comment]
Hi @majiix 
Which range slider, HTML or jQuery version?

**Comment by majiix** [comment]
![Annotation 2019-05-22 202131](https://user-images.githubusercontent.com/6815416/58189327-8ac8ca00-7ccf-11e9-8977-cf0288e25251.jpg)

It's the one in the picture above for selecting time. I've marked them with red check marks.

**Comment by man4toman** [comment]
@majiix 
Thanks for your clarification!
