### ISSUE TITLE
Notice: Undefined index: date_i18n 

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#36]
Notice: Undefined index: date_i18n in C:\xampp\htdocs\allmeme\wp-content\plugins\wp-parsidate\includes\plugins\disable.php on line 31 

[Ref](http://forum.wp-parsi.com/topic/51810-%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C-%D8%AA%D8%B5%D9%88%DB%8C%D8%B1%DB%8C-%D9%82%D9%84%D8%A7%D8%A8-%D9%87%D8%A7%DB%8C-%D9%88%D9%88%DA%A9%D8%A7%D9%85%D8%B1%D8%B3-%E2%80%93-%D8%B5%D9%81%D8%AD%D9%87-%D8%A2%D8%B1%D8%B4%DB%8C%D9%88-%D9%85%D8%AD%D8%B5%D9%88%D9%84%D8%A7%D8%AA/)

**Comment by masoudnkh** [comment]
مردیم از بس منتظر موندیم. داداشا درستش کنین ناموسا. بخدا اگه سردرمیاوردم خودم ارائه میدادم. حیف افزونه به این خوبیه پر از باگ مونده

**Comment by man4toman** [comment]
سلام
چند ریکد مهم در حال انجام هست برای همین کمی طول کشیده.

**Comment by masoudnkh** [comment]
عشقی دادا دمتون گرم
