### ISSUE TITLE
Doesn't convert date in none-Persian locale

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#37]
The plugin convert date for any locale, maybe it can be good if we use an option for it.

**Comment by amirhp-com** [comment]
As we have this line of code in file: **includes\fixes-dates.php**: 
```php
if ( get_locale() == 'fa_IR' && wpp_is_active( 'persian_date' ) ) {
```

I think we should close this issue.

**Comment by hamidrezayazdani** [comment]
@amirhp-com Yup, I think I added this in version 4.0.0, because there were so many resolved issues, I forgot to close it.

Thanks
