### ISSUE TITLE
Multi language sites integration

### ISSUE THREAD

**Issue by par6n** [wordpress-parsi/wp-parsidate#47]
The plugin should be compatible with Multi Language sites. People often use plugins such as WPML. It has been reported that Parsi Date is not compatible with these plugins.

**Comment by developernazari** [comment]
i used this code to modify the date, when current language is english:

```
add_filter( 'get_the_date', 'gregory_get_the_date', 10, 3 );
function gregory_get_the_date( $value, $format, $post ) {
    if(pll_current_language() == "en"){
       $jalaliExplode = explode("-",$value);
       $gregory = jalali_to_gregorian($jalaliExplode[0],$jalaliExplode[1],$jalaliExplode[2]);
       $value = implode("-",$gregory);
    }
    return $value;
}
```

`pll_current_language()` is actually a polylang plugin function, you must replace it with `ICL_LANGUAGE_CODE` for WPML.

also this function assumed that the date format is always Y-m-d.

**Comment by man4toman** [comment]
Done in 5.0.1.
