### ISSUE TITLE
عمل نکردن مبدل تاریخ در نسخه 5.3

### ISSUE THREAD

**Issue by noorionline** [wordpress-parsi/wp-parsidate#50]
مبدل تاریخ میلادی به شمسی بعد از آپدیت وردپرس به 5.3 عمل نمیکنه

**Comment by noorionline** [comment]
should write english?! 
in this website: http://ravi24.ir/ after update wordpress to 5.3 date converter in posts not acctived but in sidebar, date converted to persian.
![Screenshot](https://user-images.githubusercontent.com/57826904/68990435-221a6e80-0868-11ea-95af-91f8d26f0a9f.png)

**Comment by man4toman** [comment]
Hi @noorionline 
We fix this issue in our latest commits.
Thanks for report
