### ISSUE TITLE
issue with fixes_permalinks.php

### ISSUE THREAD

**Issue by amirhkhadem** [wordpress-parsi/wp-parsidate#6]
hi guys, 
the lack of you updating this plugin has caused alot of problems for alot of people that i am in contact with working in the persian wordpress community, 
i get the following message when i try to sort my posts in admin panel of wordpress by persian month, for example when i want to see all the posts for the month of "mordad" i get the following error: 

Warning: Missing argument 2 for wpp_posts_where(), called in (mysite)/wp-content/plugins/wp-parsidate/includes/admin/lists-fix.php on line 46 and defined in (mysite)/wp-content/plugins/wp-parsidate/includes/fixes-permalinks.php on line 26

Notice: Undefined variable: wp_query in (mysite)/wp-content/plugins/wp-parsidate/includes/fixes-permalinks.php on line 29

Fatal error: Call to a member function is_main_query() on null in (mysite)/wp-content/plugins/wp-parsidate/includes/fixes-permalinks.php on line 29

**Comment by amirhkhadem** [comment]
PS. this happened after the 4.8 wordpress update i think!

**Comment by man4toman** [comment]
Hi Amir,

Thank You for reporting the problem :)
We will fix this ASAP.

@amirhkhadem

**Comment by amirhkhadem** [comment]
ASAP never happened!

**Comment by man4toman** [comment]
Hi, this bug fixed and the repo will update for this weekend.

Regards
