### ISSUE TITLE
Type error in editor datepicker

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#64]
![image](https://user-images.githubusercontent.com/935397/70141116-8d0ed680-16ab-11ea-8ff5-9b00018718a0.png)

**Comment by hamidrezayazdani** [comment]
Solved in [this](https://github.com/wordpress-parsi/wp-parsidate/pull/94/commits/5c6a2a561dcd7034ab3a368448f2f59cd3c146ef) commit.
