### ISSUE TITLE
Documentation for wpp_settings[dis_input]

### ISSUE THREAD

**Issue by mojiAh** [wordpress-parsi/wp-parsidate#66]
can you provide an example of how to set the input to get a class filtered by your plugin?
i.e I have a css class named 'nonFarsi' and I would like this class would be excluded by the plugin. I've gone through the code you provided but maybe my poor understanding of php made me to ask it here. 
<img width="1382" alt="Screenshot 2019-12-06 at 15 36 38" src="https://user-images.githubusercontent.com/15276225/70327157-dcd1d700-183e-11ea-80f3-a17a1591ad46.png">

**Comment by man4toman** [comment]
Related #22

**Comment by mojiAh** [comment]
میشه لطفا برای این مورد همینجا خیلی خلاصه راه حل رو بنویسید. من میخوام یک کلاس به نام موردنظر از تنظیمات فارسی فیلتر بشه. متاسفانه این فیلتر اعمال نمیشه به اون شکلی که توی عکس میبینید.
