### ISSUE TITLE
Direction problem in legacy editor

### ISSUE THREAD

**Issue by CG-TEAM** [wordpress-parsi/wp-parsidate#67]
با سلام و احترام

یه مشکلی که بهش برخورد کردم با افزونه پارسی دیت نگارش 3.0.3 
اینه که در تصویری که پیوست کردم، وقتی افزونه فعاله بخش متن ویرایشگر چپ چین میشه و نمیشه راست چینش کرد به محض اینکه غیرفعال میکنم درست میشه.مورد بعد اینکه ویرایش پست یا برگه که میزنم. مستقیم بصورت پیشفرض ویرایشگر متن باز میشه دیداری باز نمیشه پیشفرض. وقتی غیرفعال میکنم افزونه ره مشکل برطرف میشه.

![photo_2019-12-17_10-02-45](https://user-images.githubusercontent.com/32476992/70970803-9721d380-20b4-11ea-82a4-64acbc816f88.jpg)

**Comment by hamidrezayazdani** [comment]
I tested this in the following versions, no problem:
WordPress: 5.7.2 and 5.8
Parsidate: 4.0.0
