### ISSUE TITLE
دراپ دان بخش رسانه

### ISSUE THREAD

**Issue by unique2world** [wordpress-parsi/wp-parsidate#69]
سلام
@man4toman 
این ایرادم فیکسش کنید
سپاس  

[http://s6.picofile.com/file/8382408684/photo_2019_12_21_23_16_06.jpg](url)

**Comment by mehrshaddarzi** [comment]
@man4toman 
Please Check this pull request.

https://github.com/wordpress-parsi/wp-parsidate/pull/72

screenshot:
http://uupload.ir/files/6n0_28569.jpg

**Comment by man4toman** [comment]
Thanks @mehrshaddarzi 
I'm going to close this issue.
