### ISSUE TITLE
conflict with jetpack

### ISSUE THREAD

**Issue by amirhkhadem** [wordpress-parsi/wp-parsidate#7]
i have yet another issue to report about your plugin, im beginning to think i may need to change my persian calendar plugin because of the no update agenda that you guys are following!

a very annoying encounter is that all my users are having a problem with  a conflict that your plugin has with the **jetpack** plugin, 

_**the conflict**_ is a an error message we receive on **editing a post**

i receive the below message 

`Failed to load content css: http://www.example.com/wp-content/plugins/jetpack/modules/videopress/css/videopress-editor-style-rtl.css`

and i know for a fact its from your plugin because when i disable parsidate i dont have the problem anymore.

**Comment by man4toman** [comment]
This bug fixed in previous update

Regards
