### ISSUE TITLE
week-end dates are highlighted incorrectly

### ISSUE THREAD

**Issue by KingMatrix1989** [wordpress-parsi/wp-parsidate#74]
با سلام و احترام.
اینطور که متوجه شدم در فایل
datepicker.js
کلاس سی.اس.اس
ui-datepicker-week-end
روی روزهای شنبه و یکشنبه در نظر گرفته شده و مشخصه که این قسمت در کتابخانه نیاز به تغییر داره

**Comment by KingMatrix1989** [comment]
<img width="191" alt="Annotation 2020-04-13 234508" src="https://user-images.githubusercontent.com/12100097/79152490-8cb4e380-7de1-11ea-877c-e6ba736e1302.png">

**Comment by hamidrezayazdani** [comment]
In version 4, the **jquery pertsian datepicker** is no longer used, I close this
