### ISSUE TITLE
Default timezone problem

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#80]
Related:
https://wp-parsi.com/support/topic/53779-%D9%85%D8%B4%DA%A9%D9%84-%D9%85%D9%86%D8%B7%D9%82%D9%87-%D8%B2%D9%85%D8%A7%D9%86%DB%8C-%D9%BE%DB%8C%D8%B4%D9%81%D8%B1%D8%B6-%D8%A8%D8%B9%D8%AF-%D8%A7%D8%B2-%D8%A2%D9%BE%D8%AF%DB%8C%D8%AA-%D9%88%D8%B1%D8%AF%D9%BE%D8%B1%D8%B3-%D8%A8%D9%87-%D9%86%D8%B3%D8%AE%D9%87-54/

**Comment by hamidrezayazdani** [comment]
I tested with the following versions, nothing is seen:
WordPress: 5.7.2 And 5.8
ParsiDate: 3.0.3 And 4.0.0
![localhost-site-health](https://user-images.githubusercontent.com/40775953/132053884-4fe1ae9c-689a-48d6-88dd-6154fa5a46a5.png)
