### ISSUE TITLE
problem with rank math plugin

### ISSUE THREAD

**Issue by SeyedAliHossaini** [wordpress-parsi/wp-parsidate#82]
Hi , I want use rank math plugin but it has conflict with parsidate. Please help me I love rank math and parsidate is a necessary plugin for my site . what i can do?

**Comment by man4toman** [comment]
Hi @SeyedAli-jsf1010 
Please give us more information about the conflict.

**Comment by hamidrezayazdani** [comment]
Duplicated with #99
