### ISSUE TITLE
New style for date widgets

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#85]

**Comment by hamidrezayazdani** [comment]
In version 4, an option to select a color mode has been added. Selecting dark or light mode changes the appearance of the widget.

The colors used are based on official Google documentation for [dark mode](https://material.io/design/color/dark-theme.html).

Also, the weekends are displayed in different colors. The color of this section is also based on the global accessibility standard published in [W3C](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) and AAA quality
