### ISSUE TITLE
WooCommerce support

### ISSUE THREAD

**Issue by man4toman** [wordpress-parsi/wp-parsidate#86]
Task issue.

**Comment by hamidrezayazdani** [comment]
WooCommerce uses **date_i18n** to convert order dates

Using this [hook](https://developer.wordpress.org/reference/hooks/date_i18n/) is also not the right thing to do.

We are currently using a few tricks to turn history into some parts. It is unlikely that the WooCommerce team will work with us to make major changes. I think we did the best we could.
