### ISSUE TITLE
dokan date not converted

### ISSUE THREAD

**Issue by masoudnkh** [wordpress-parsi/wp-parsidate#89]
با سلام و خسته نباشید خدمت مرتضی جان عزیز
یه مشکلی هست که اگه حلش کنید یه دنیا ممنونم ازتون. افزونه پارسی دیت تاریخ های دکان رو تغییر نمیده و همون انگلیسی هستند. یعنی مینویسه فوریه

این مشکل داخل بخشی در داشبورد ، در قسمت " فروش این ماه" مشاهده کردم.
![56re](https://user-images.githubusercontent.com/3355596/109414425-1bb1f680-79c8-11eb-9bab-1f236863d848.JPG)

این بخش از دکان هم مشکل داره ، تقویمش تاریخ نوشته به شمسی ولی میزنی روش میلادی میاره
![345re](https://user-images.githubusercontent.com/3355596/109414458-4603b400-79c8-11eb-91ec-b6486a569cc1.JPG)

. مشکل دیگه هم هست اینکه تاریخ رو اشتباه میزنه توی بخش سفارشات در داشبورد دکان تصویر ضمیمه کردم. نوشته آذر و سال 777 در صورتی که باید اسفند 1399 باشه. وقتی هاور میشه روش درسته ولی متن اصلی اشتباه.
![dfe](https://user-images.githubusercontent.com/3355596/109414394-e0172c80-79c7-11eb-87ff-55d9d87c9d24.JPG)

**Comment by hamidrezayazdani** [comment]
Unfortunately, the Dokan plugin doesn't use the correct WordPress date structure for its reports. This issue should be discussed with the developers of the Dokan to review a large part of the plugin core code.
