### ISSUE TITLE
Problem with `YITH_WC_Product_Countdown` plugin and forced changing date field to Jalali date

### ISSUE THREAD

**Issue by Mehran91z** [wordpress-parsi/wp-parsidate#93]
There is bug with using v3.0.3 and `yith woocommerce countdown` plugin, So we need to have Gregorian date in 'countdown section' in product edit page, but Parsidate will changed it in Jalali date after page load.

So I've added this line in 'hook list' textarea field in Parsidate plugin settings page:
`date_i18n,write_tab_options,YITH_WC_Product_Countdown`

But the problem changed and not solved!
Now we will see "Y-m-d" text in date field noticed above in product edit page.

The problem fixed (not by standard way) after changed this line:
_wp-parsidate/includes/fixes-dates.php:161:_
```
return $format;
```
to:
```
return date($format, $timestamp);
```
 
So please check it out and fix it by standard way as you know.
Thanks in advance.

**Comment by Mehran91z** [comment]
Oh, I see that now its solved in `v3.2.0-alpha` in `master` branch.
Thank you.

**Comment by Mehran91z** [comment]
In new version 4.0.0 it does not work again and set date field to "Y-m-d" after save!

Please check it out.

**Comment by man4toman** [comment]
As I see, this is a premium plugin, we don't have any support for premium plugins but if you purchased the original version, let us know.

**Comment by man4toman** [comment]
I'm going to close this issue due to inactivity.
