### ISSUE TITLE
Parsi Datepicker On Another Plugins with parsidate

### ISSUE THREAD

**Issue by zir4k** [wordpress-parsi/wp-parsidate#96]
سلام و وقت بخیر
متاسفانه بعد از کلی گشت و گذار در فضای وب
در زمینه ترجمه تقویم در پلاگین ها یا به عبارتی datepicker هیچ مقاله آموزشی پیدا نکردم
حدالامکان تمام پلاگین های شمسی ساز و فارسی ساز رو نصب کردم اما در قسمتی که مد نظرم بود ترجمه صورت نگرفت
کلیت کار من با پلاگین های جت یک فرم ایجاد کردم که دارای 2 تا فیلد هست ، یکی نام شخص یکی تاریخ همین! من قسمت تاریخی که کاربر میخواید انتخاب بکنه رو نیاز هست شمسی بکنم کسی هست تو این زمینه بتونه کمکی بکنه؟ در صورتی که راه حلی برای این موضوع دارید ارائه بدید با تشکر از همراهی شما.
![image](https://user-images.githubusercontent.com/60684082/133956812-41acd359-d234-4277-a490-576b3f733c81.png)
تصویر ضمیمه شد

**Comment by amirhp-com** [comment]
سلام برای شمسی سازی پلاگینی که فرمودید میتونم کمک تون کنم
https://hpv.im/
