### ISSUE TITLE
Post time reset to zero / Calendar color in widget not aplied

### ISSUE THREAD

**Issue by ghost** [wordpress-parsi/wp-parsidate#97]
Hi
Thanks for updating this plugin
I have test and found 2 issue:
1-The post time will reset to 0:00 when enabling plugin with all items activated or even just plugin is active but the rest of settings are deactive.
2-I chose 2 Calendar in widget area for see different between Light and Dark but the result was the same , It means all 2 widget are Light.

Theme: Betheme from muffin builder version 25.0.3
Plugin used: 
All In One WP Security Version 4.4.9
FileBird Version 4.9.1
LiteSpeed Cache Version 4.4.2
Rank Math SEO Version 1.0.72 
SearchWP Live Ajax Search Version 1.6.1
Secondary Title Version 2.0.8
Slider Revolution Version 6.5.8

Thanks

**Comment by hamidrezayazdani** [comment]
Both of these issues resolved in #125
